// ============================================================================
// Строки интерфейса билетного сервиса. Пары { ru, en } лежат рядом:
// переводчик видит оригинал и перевод вместе, и потерять одну версию
// незаметно невозможно — за этим следит тест.
// ============================================================================

export const STRINGS = {
  mapSwitched: { ru: 'к конкуренту', en: 'to the rival' },
  mapOutage: { ru: '{share} спроса не поместилось на старте продаж', en: '{share} of demand never got through at on-sale' },
  leverInertPlatform: {
    ru: 'Пока виджет не стоит ни у одного организатора, это решение ни на что не влияет: подключите тип организаторов в панели каналов продаж.',
    en: 'Until at least one organiser has the widget, this decision changes nothing: onboard an organiser type in the sales-channels panel.',
  },
  marketMapTitle: { ru: 'Двусторонний рынок', en: 'The two-sided market' },
  mapOrgs: { ru: 'организаторы', en: 'organisers' },
  mapOrgsSub: { ru: 'с виджетом {connected}', en: '{connected} with the widget' },
  mapBuyers: { ru: 'зрители', en: 'buyers' },
  mapBuyersSub: { ru: 'ваша доля рынка {share}', en: 'your market share {share}' },
  // Внутри SVG нельзя HTML-теги: <b> выбрасывает парсер из режима SVG,
  // и вся схема разваливается в строку текста (проверено вживую).
  readoutTake: {
    ru: 'Вы забираете <b>{rate}</b> оборота — {perTicket} с билета. Эквайринг съедает {acquiring} оборота, и берётся он до вас.',
    en: 'You keep <b>{rate}</b> of turnover — {perTicket} per ticket. Card fees eat {acquiring} of turnover, and they come off the top, before your share.',
  },
  readoutTakeSplit: {
    ru: 'Из них через афишу {market}, через виджет {widget}. Сбор и комиссия идут вместе: зритель платит один, организатор — другую.',
    en: 'Of that, {market} comes through the listings and {widget} through the widget. Fee and commission travel together: the buyer pays one, the organiser the other.',
  },
  readoutSides: {
    ru: 'Организаторов <b>{orgs}</b>, из них с виджетом {connected}. Ваша доля рынка организаторов — {share}.',
    en: 'Organisers: <b>{orgs}</b>, {connected} of them with the widget. Your share of the organiser market is {share}.',
  },
  readoutFill: {
    ru: 'Заполняемость залов <b class="{cls}">{fill}</b>, перекупщики забрали {bots} билетов.',
    en: 'Hall fill rate <b class="{cls}">{fill}</b>; resellers took {bots} of tickets.',
  },
  readoutTrust: {
    ru: 'Доверие <b class="{cls}">{trust}</b>, уровень сервиса {service}. Копится медленно, рушится быстро.',
    en: 'Trust <b class="{cls}">{trust}</b>, service level {service}. Slow to build, quick to break.',
  },
  budgetTitle: { ru: 'Расходы этого месяца при текущих настройках: <b>{total}</b>', en: 'This month’s spend at current settings: <b>{total}</b>' },
  budgetDemand: { ru: 'спрос', en: 'demand' },
  budgetSupply: { ru: 'организаторы', en: 'organisers' },
  budgetProduct: { ru: 'продукт и поддержка', en: 'product and support' },
  budgetTech: { ru: 'технологии', en: 'technology' },
  budgetFixed: { ru: 'фикс и штат', en: 'fixed and staff' },
  budgetNet: { ru: 'Вклад прошлого месяца {contribution} → итог примерно <b class="{cls}">{net}</b>.', en: 'Last month’s contribution {contribution} → roughly <b class="{cls}">{net}</b>.' },
  policyCustom: { ru: 'своё значение', en: 'custom value' },
  pnlFinance: { ru: 'Финансовая команда', en: 'Finance team' },
  pnlMisc: { ru: 'Прочие расходы ({rate} выручки)', en: 'Miscellaneous ({rate} of revenue)' },
  brand: { ru: 'БИЛЕТВИЛЬ', en: 'TICKETGRAD' },
  brandSub: { ru: 'симулятор билетного сервиса', en: 'ticketing marketplace simulator' },
  btnRestart: { ru: 'Заново', en: 'Restart' },
  btnRestartTitle: { ru: 'Начать заново. Город сделает вид, что ничего не было.', en: 'Start over. The city will pretend nothing happened.' },
  langToggle: { ru: 'EN', en: 'RU' },
  langTitle: { ru: 'Switch to English', en: 'Переключить на русский' },

  // --- Шапка ---
  kpiMonth: { ru: 'Месяц', en: 'Month' },
  kpiCash: { ru: 'Касса', en: 'Cash' },
  kpiCashOut: { ru: 'деньги кончились', en: 'out of money' },
  kpiRunway: { ru: 'хватит на {months} мес', en: '{months} months of runway' },
  kpiProfitable: { ru: 'операционно прибыльны', en: 'operationally profitable' },
  kpiOrgs: { ru: 'Организаторы', en: 'Organisers' },
  kpiOrgsSub: { ru: 'у конкурента {them}', en: 'rival has {them}' },
  kpiShare: { ru: 'Доля рынка', en: 'Market share' },
  kpiShareSub: { ru: 'по договорам, не по билетам', en: 'by contracts, not by tickets' },
  kpiGmv: { ru: 'Оборот', en: 'Turnover' },
  kpiGmvSub: { ru: 'ваша выручка {revenue}', en: 'your revenue {revenue}' },
  kpiProfit: { ru: 'Прибыль / мес', en: 'Profit / mo' },
  kpiProfitSub: { ru: 'вклад {value}', en: 'contribution {value}' },
  kpiEquity: { ru: 'Оценка × доля', en: 'Valuation × stake' },
  kpiEquitySub: { ru: 'ваша доля {value}', en: 'your stake {value}' },
  kpiStart: { ru: 'Старт', en: 'Start' },
  kpiStartSub: { ru: 'деньги инвестора, 100% ваши', en: 'investor money, 100% yours' },
  kpiFlat: { ru: 'без изменений', en: 'flat' },

  // --- Кнопки ---
  btnNext: { ru: 'Сыграть месяц {month} →', en: 'Run month {month} →' },
  btnResults: { ru: 'Итоги партии', en: 'Final results' },
  restartTitle: { ru: 'Начать заново?', en: 'Start over?' },
  restartText: { ru: 'Текущая партия будет потеряна.', en: 'The current game will be lost.' },
  restartYes: { ru: 'Да, заново', en: 'Yes, restart' },
  restartNo: { ru: 'Отмена', en: 'Cancel' },
  // --- Приветственный экран ---
  welcomeTitle: { ru: '🎟️ Вы управляете билетным сервисом', en: '🎟️ You are running a ticketing service' },
  welcomeRole: { ru: 'Оператор «БИЛЕТВИЛЬ» — сайт, где покупают билеты. Театрам, промоутерам, клубам и стадионам нужно продать зал, зрителям — куда-то сходить; вы решаете, сколько взять с тех и с других.', en: 'TICKETGRAD is the site where people buy tickets. Theatres, promoters, clubs and stadiums need to fill halls, audiences need somewhere to go; you decide what to charge each side.' },
  welcomeTurn: { ru: '<b>Один ход — месяц,</b> партия — три года. Год начинается в сентябре — с открытия театрального сезона.', en: '<b>One turn is a month,</b> a game is three years. The year starts in September, with the opening of the theatre season.' },
  welcomeTension: { ru: '<b>В чём подвох.</b> Зрители идут туда, где афиша, организаторы — где зрители: реклама пустой афиши сжигает деньги, пустые залы разгоняют организаторов. А миллиарды в обороте — не ваши: ваши — несколько процентов сверху, и часть сразу забирает банк.', en: '<b>Here is the catch.</b> Buyers go where the listings are, organisers go where the buyers are: advertising an empty listing burns money, and empty halls drive organisers away. The tens of millions flowing through you are not yours either: yours is a few percent on top, and the bank takes part of that straight away.' },
  welcomeGoal: { ru: '<b>Проиграть не страшно:</b> растерять организаторов и понять, с какого решения это началось, — полезнее, чем случайно выжить.', en: '<b>Losing is fine:</b> losing organisers and seeing which decision started it teaches more than surviving by accident.' },
  welcomeStart: { ru: 'Начать', en: 'Start' },
  welcomeMore: { ru: 'Подробнее', en: 'Details' },
  welcomeHint: { ru: '<b>Первый ход</b> можно сделать, ничего не трогая. У каждого ползунка есть «зачем это?», разбор хода игра пишет сама, подробности — за кнопкой «?».', en: '<b>Your first turn</b> can be played without touching anything. Every slider has a “why does this matter?”, the game explains each turn itself, and the “?” button has the rest.' },
  helpModalTitle: { ru: 'Как устроена игра', en: 'How the game works' },
  helpModalOk: { ru: 'Понятно', en: 'Got it' },
  helpAuthor: { ru: 'Игру сделал <b><a href="https://www.linkedin.com/in/ruben-deev" target="_blank" rel="noopener">Ruben Deev</a></b>. Лицензия <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ru" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>: свободно для учёбы и некоммерческого использования с указанием автора.', en: 'Made by <b><a href="https://www.linkedin.com/in/ruben-deev" target="_blank" rel="noopener">Ruben Deev</a></b>. Licensed <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>: free for education and non-commercial use with attribution.' },
  helpVersion: { ru: 'Сборка {version} от {date}.', en: 'Build {version}, {date}.' },
  algosPending: { ru: '✓ Будет внедрён', en: '✓ Installing' },
  algosPendingHint: { ru: 'Внедрение и списание произойдут при расчёте месяца. Нажмите ещё раз, чтобы отменить.', en: 'It will be installed and charged when the month is run. Click again to cancel.' },
  algosPendingToast: { ru: '«{name}» будет внедрён при расчёте месяца.', en: '“{name}” will be installed when the month runs.' },
  // Ироничные подписи к вердиктам: шутка подсвечивает исход, не заменяя
  // шкалу. Тексты одинаковы во всех играх набора — это голос города.
  // Тихий ход: показывается изредка, чтобы тишина была частью мира,
  // а не пустым местом (и не надоедала)
  quietQuip1: { ru: 'Тихий месяц. Подозрительно тихий.', en: 'A quiet month. Suspiciously quiet.' },
  quietQuip2: { ru: 'Городу нечем вас удивить. Пока.', en: 'The city has nothing to surprise you with. Yet.' },
  quietQuip3: { ru: 'Событий нет. Конкурент, вероятно, тоже отдыхает. Вероятно.', en: 'No events. The rival is probably resting too. Probably.' },
  gradeQuipExcellent: { ru: 'Город делает вид, что не сомневался.', en: 'The city pretends it never doubted you.' },
  gradeQuipSolid: { ru: 'Совет директоров аплодирует. Сидя, но искренне.', en: 'The board applauds — seated, but sincere.' },
  gradeQuipSurvived: { ru: 'Инвесторы называют это «опытом».', en: 'Investors call this “experience”.' },
  gradeQuipModest: { ru: 'Совет директоров вежливо смотрит на часы.', en: 'The board politely checks its watch.' },
  gradeQuipBankrupt: { ru: 'Деньги кончились раньше, чем аргументы. Бывает у лучших — обычно как раз у лучших.', en: 'The money ran out before the arguments did. Happens to the best — usually precisely to them.' },
  gradeQuipSold: { ru: 'Продажа — тоже выход. Просто дверь поуже.', en: 'A sale is an exit too. Just a narrower door.' },
  gradeScale: { ru: 'Шкала: «отлично» — доля рынка от 45% при take rate от 9%; «крепкий результат» — итог от {a}. Сильные игроки доводят платформенную партию до 15–20 млрд ₽ — выжить легко, выиграть нет.', en: 'The scale: “excellent” is 45%+ market share at a 9%+ take rate; “solid” starts at {a}. Strong players push a platform run to $150–200M — surviving is easy, winning is not.' },
  helpVersionDev: { ru: 'Сборка из исходников (не раздаваемый файл).', en: 'Built from source (not a distributed file).' },
  crashTitle: { ru: 'Игра не смогла запуститься', en: 'The game failed to start' },
  crashText: { ru: 'Скорее всего, браузер слишком старый или сохранение осталось от другой версии. Сохранение уже сброшено — попробуйте перезапустить.', en: 'Most likely the browser is too old, or the save is left over from another version. The save has been cleared — try restarting.' },
  crashReset: { ru: 'Перезапустить', en: 'Restart' },
  crashBrowser: { ru: 'Если не помогло — пришлите текст выше: по нему видно, чего не хватает браузеру.', en: 'If that did not help, send the text above: it shows what the browser is missing.' },
  jumpGo: { ru: 'перейти →', en: 'go there →' },

  // --- Рычаги ---
  titleLevers: { ru: 'Рычаги бизнеса', en: 'Business levers' },
  leverWhy: { ru: 'зачем это?', en: 'why does this matter?' },

  // --- Итоги месяца ---
  reportTitle: { ru: 'Итоги месяца {month}', en: 'Month {month} results' },
  reportHeadStats: {
    ru: 'оборот {gmv} · ваша выручка {revenue} · с билета {perTicket}',
    en: 'turnover {gmv} · your revenue {revenue} · per ticket {perTicket}',
  },
  reportMonth0: { ru: 'Месяц 0. Продажи ещё не начались.', en: 'Month 0. Sales have not started yet.' },
  reportStartTitle: { ru: 'С чего начать.', en: 'Where to start.' },
  reportStartIntro: {
    ru: 'У вас {cash} и небольшой список организаторов. Порядок примерно такой:',
    en: 'You have {cash} and a short list of organisers. The sequence is roughly this:',
  },
  reportStart1: {
    ru: 'Решите, кому поставить <a class="jump" data-jump="panel:channel">билетный виджет</a> — вашу продажу билетов прямо на сайте организатора. Без него тысячи мелких клубов до вас просто не дойдут: обслуживать их руками нерентабельно.',
    en: 'Decide who gets a <a class="jump" data-jump="panel:channel">ticketing widget</a> — your ticket sales embedded in the organiser\'s own site. Without it thousands of small clubs never reach you: serving them by hand does not pay.',
  },
  reportStart2: {
    ru: 'Разделите комиссию между <a class="jump" data-jump="lever:buyerFee">сбором с покупателя</a> и <a class="jump" data-jump="lever:orgCommission">комиссией с организатора</a>. Сумма одна, последствия разные.',
    en: 'Split your take between the <a class="jump" data-jump="lever:buyerFee">buyer fee</a> and the <a class="jump" data-jump="lever:orgCommission">organiser commission</a>. The sum is the same, the consequences are not.',
  },
  reportStart3: {
    ru: 'Наймите <a class="jump" data-jump="lever:managers">аккаунт-менеджеров</a>: перегруженная команда теряет организаторов быстрее, чем приводит новых.',
    en: 'Hire <a class="jump" data-jump="lever:managers">account managers</a>: an overloaded team loses organisers faster than it signs them.',
  },
  reportStart4: {
    ru: 'И только потом включайте <a class="jump" data-jump="lever:marketing">маркетинг</a>. Приводить зрителей в пустую афишу — самый дорогой способ ничего не продать.',
    en: 'Only then turn on <a class="jump" data-jump="lever:marketing">marketing</a>. Bringing buyers to empty listings is the most expensive way to sell nothing.',
  },
  reportStartAlgos: {
    ru: 'Умные механики откроются позже: им нужны данные, а данные берутся из проданных билетов.',
    en: 'The smart mechanics unlock later: they need data, and data comes from tickets sold.',
  },

  statOrgs: { ru: 'Организаторы', en: 'Organisers' },
  statOrgsSub: { ru: '+{gained} / −{lost}', en: '+{gained} / −{lost}' },
  statTickets: { ru: 'Билетов продано', en: 'Tickets sold' },
  statTicketsSub: { ru: 'через афишу {market}', en: '{market} via listings' },
  statGmv: { ru: 'Оборот', en: 'Turnover' },
  statGmvSub: { ru: 'через афишу {share}', en: '{share} via listings' },
  statTake: { ru: 'Ваша доля оборота', en: 'Your take rate' },
  statTakeSub: { ru: 'эквайринг съедает {acq}', en: 'card fees eat {acq}' },
  statFill: { ru: 'Заполняемость', en: 'Fill rate' },
  statFillSub: { ru: 'мест выставлено {seats}', en: '{seats} seats listed' },
  statReach: { ru: 'Охват', en: 'Reach' },
  statReachSub: { ru: '{share} потенциала · конверсия {conv}', en: '{share} of potential · conversion {conv}' },
  statTrust: { ru: 'Доверие', en: 'Trust' },
  statTrustSub: { ru: 'перекупщики забрали {bots}', en: 'resellers took {bots}' },
  statService: { ru: 'Обслуживание', en: 'Service level' },
  statServiceSub: { ru: 'на менеджера {perManager}', en: '{perManager} per manager' },
  statProfit: { ru: 'Прибыль', en: 'Profit' },
  statProfitSub: { ru: 'постоянные {value}', en: 'fixed costs {value}' },
  statBreadth: { ru: 'Разнообразие афиши', en: 'Listing breadth' },
  statBreadthSub: { ru: 'событий {events}', en: '{events} events' },
  statBuyerPref: { ru: 'Выбор зрителя', en: 'Buyer choice' },
  statBuyerPrefSub: { ru: 'ваш сбор {fee} · у конкурента {rival}', en: 'your fee {fee} · rival {rival}' },
  statPlatform: { ru: 'Платформа', en: 'Platform' },
  statPlatformSub: { ru: 'подключено {count} организаторов', en: '{count} organisers connected' },

  // --- Разбор месяца ---
  driversTitle: { ru: 'Из чего сложилось изменение числа организаторов ({delta})', en: 'What drove the change in organiser count ({delta})' },
  driversNet: { ru: 'Итого', en: 'Net' },
  flowJoined: { ru: 'Новые договоры', en: 'New contracts' },
  flowLeft: { ru: 'Ушли', en: 'Left' },
  flowSwitch: { ru: 'Переток с конкурентом', en: 'Net switching with the rival' },
  factorsIntro: { ru: 'Условия месяца изменились так:', en: 'This month’s conditions changed as follows:' },
  factorAppeal: { ru: 'привлекательность для организаторов', en: 'appeal to organisers' },
  factorStanding: { ru: 'позиция против конкурента', en: 'standing against the rival' },
  factorFill: { ru: 'заполняемость', en: 'fill rate' },
  factorReach: { ru: 'охват аудитории', en: 'audience reach' },
  factorTrust: { ru: 'доверие', en: 'trust' },
  factorService: { ru: 'обслуживание', en: 'service level' },
  factorConversion: { ru: 'конверсия', en: 'conversion' },

  // --- Предупреждения ---
  alertsMore: { ru: 'скрыто замечаний: {count}', en: '{count} more notes hidden' },
  alertNoListings: { ru: 'Афиша почти пуста: мест {seats}. Маркетинг сейчас сгорает впустую — приводить зрителя некуда.', en: 'The listings are nearly empty: {seats} seats. Marketing burns for nothing right now — there is nowhere to bring buyers.' },
  alertLowFill: { ru: 'Заполняемость {fill}: организаторы видят пустые залы и уходят. Либо больше спроса, либо меньше афиши.', en: 'Fill rate {fill}: organisers see empty halls and leave. Either more demand or fewer listings.' },
  alertOverloaded: { ru: 'Менеджеры перегружены: качество обслуживания {service}. На каждого приходится {perManager} организаторов.', en: 'The managers are overloaded: service level {service}. Each one carries {perManager} organisers.' },
  alertFeeHigh: { ru: 'Ваш сбор {fee} против {rival} у конкурента. Зритель сравнивает итоговую цену: спрос уже {pref} от паритета.', en: 'Your fee is {fee} against the rival’s {rival}. Buyers compare the final price: demand is already {pref} of what it would be at price parity.' },
  alertCommissionHigh: { ru: 'Комиссия {value} — организаторы считают каждый процент, и конкурент это знает.', en: 'Commission at {value} — organisers count every percent, and the rival knows it.' },
  alertTrustLow: { ru: 'Доверие упало до {value}. Оно возвращается месяцами, а тратится за один плохой старт продаж.', en: 'Trust has fallen to {value}. It comes back over months and is spent in one bad on-sale.' },
  alertBots: { ru: 'Перекупщики забрали {share} билетов на хитах. Оборот это даже поднимает, доверие — нет.', en: 'Resellers took {share} of tickets on the hits. It even lifts turnover; it does not lift trust.' },
  alertOutage: { ru: 'На старте продаж потеряно {share} спроса: мощности не хватило.', en: '{share} of demand lost at on-sale: not enough capacity.' },
  alertPlatformThin: { ru: 'Через афишу идёт только {share} оборота. Виджеты удержали организаторов, но с билета, проданного на их сайте, вы получаете в разы меньше.', en: 'Only {share} of turnover goes through your listings. The widgets kept the organisers, but a ticket sold on their own site earns you several times less.' },
  alertNoOnboarding: { ru: 'Тип выбран, а бюджет на подключения нулевой — переезд не идёт. Виджет не включается кнопкой: у каждого организатора уже что-то стоит, и за интеграцию, перенос залов и обучение кассиров надо платить. Пока не платите, всё остаётся как было.', en: 'You picked the type but the onboarding budget is zero, so nobody is moving. The widget does not switch on with a button: every organiser already runs something, and integration, porting the halls and training the box office all have to be paid for. Until you pay, nothing changes.' },
  alertNoPlatform: { ru: 'Клубам и стендапу нужен билетный виджет: их тысячи, и вручную их не обслужить. Сейчас они идут к конкуренту.', en: 'Clubs and stand-up need a ticketing widget: there are thousands of them and no way to serve them by hand. Right now they go to the rival.' },
  alertTakeThin: { ru: 'Ваша доля оборота {take} при эквайринге {acq}. На вас остаётся почти ничего.', en: 'Your take rate is {take} against {acq} in card fees. Almost nothing is left for you.' },
  alertProfit: { ru: 'Месяц закрыт в плюс: {value}.', en: 'The month closed in the black: {value}.' },
  alertRivalCut: { ru: 'Конкурент срезал комиссию до {value}. Организаторы уже считают.', en: 'The rival cut commission to {value}. Organisers are already doing the maths.' },
  alertRivalDead: { ru: 'Конкурент ушёл с рынка. Рынок ваш — и теперь только вы отвечаете за то, что на нём происходит.', en: 'The rival has left the market. It is yours — and now you alone answer for what happens on it.' },
  alertLosingOrgs: { ru: 'Конкурент забрал {count} организаторов за месяц.', en: 'The rival took {count} organisers this month.' },
  alertWinningOrgs: { ru: 'Вы переманили {count} организаторов у конкурента.', en: 'You took {count} organisers from the rival.' },
  alertAlgosReady: { ru: 'Данных хватает, чтобы включить: {names} (качество {quality}).', en: 'There is enough data to switch on: {names} (quality {quality}).' },
  alertRndIdle: { ru: 'Команда данных стоит {cost} и не используется: качество {quality}, но ни один алгоритм не включён.', en: 'The data team costs {cost} and does nothing: quality {quality}, but no algorithm is on.' },
  alertCapped: { ru: 'Акционеры срезали маркетинг до {cap} — это последствие проваленной цели.', en: 'The shareholders capped marketing at {cap} — the consequence of a missed goal.' },
  alertGoalPassed: { ru: 'Цель {year}-го года выполнена. Оценка компании выросла.', en: 'The year {year} goal is met. The valuation went up.' },
  alertGoalFailed_dilution: { ru: 'Цель первого года провалена. Акционеры вводят деньги сами и режут вашу долю.', en: 'The first year goal was missed. The shareholders put money in themselves and cut your stake.' },
  alertGoalFailed_marketingCap: { ru: 'Цель второго года провалена. Маркетинг урезан на полгода.', en: 'The second year goal was missed. Marketing is capped for six months.' },
  alertGoalFailed_valuation: { ru: 'Цель третьего года провалена. Оценка компании падает.', en: 'The third year goal was missed. The valuation falls.' },
  alertCrisisResolved: { ru: '«{name}» улажено. Обошлось в {cost}.', en: '“{name}” is settled. It cost {cost}.' },

  // --- Ход ---
  turnTitle: { ru: 'Месяц {month}: ваш ход', en: 'Month {month}: your move' },
  turnNothing: { ru: 'На этот месяц ничего не запланировано', en: 'Nothing planned for this month' },
  turnPlanned: { ru: 'запланировано: {list}', en: 'planned: {list}' },
  todoPlatformTitle: { ru: 'Виджет не стоит ни у кого', en: 'Nobody has the widget' },
  todoPlatformText: { ru: 'Длинный хвост мелких организаторов до вас не дойдёт: обслуживать их руками нерентабельно.', en: 'The long tail of small organisers will never reach you: serving them by hand does not pay.' },
  todoManagersTitle: { ru: 'Менеджеры перегружены', en: 'The managers are overloaded' },
  todoManagersText: { ru: 'На каждого приходится {perManager} организаторов вместо {norm}. Они уходят молча.', en: 'Each carries {perManager} organisers instead of {norm}. They leave without a word.' },
  todoCapacityTitle: { ru: 'Нет запаса мощности', en: 'No capacity headroom' },
  todoCapacityText: { ru: 'В месяц с хитом сайт ляжет на старте продаж, и это увидят все сразу.', en: 'In a month with a hit the site will go down at on-sale, and everyone will see it at once.' },
  todoFeeTitle: { ru: 'Сбор выше, чем у конкурента', en: 'Your fee is above the rival’s' },
  todoFeeText: { ru: 'Зритель сравнивает итоговую цену и уходит туда, где дешевле.', en: 'Buyers compare the final price and go where it is cheaper.' },

  // --- Каналы и платформа ---
  mapTitle: { ru: 'Кварталы рынка: типы организаторов', en: 'City blocks of the market: organiser types' },
  qtShare: { ru: 'ваша доля {p}', en: 'your share {p}' },
  qtOwn: { ru: 'мимо вас {p}', en: 'past you {p}' },
  qtWidget: { ru: 'виджет ✓ {p}', en: 'widget ✓ {p}' },
  qtNoWidget: { ru: 'виджета нет', en: 'no widget' },
  qtLoss: { ru: '−{n} орг. за месяц', en: '−{n} orgs this month' },
  qtTotal: {
    ru: 'Оборот рынка за месяц {all}; через вас — {mine} ({share}).',
    en: 'Monthly market turnover {all}; {mine} of it went through you ({share}).',
  },
  qtKeyShare: { ru: 'заливка — ваша доля оборота', en: 'fill — your share of turnover' },
  qtKeyWidget: { ru: 'виджет развёрнут', en: 'widget deployed' },
  qtKeyOwn: { ru: 'мимо вас — своя касса', en: 'past you — their box office' },
  qtKeyLoss: { ru: 'тип теряет организаторов', en: 'the type is losing organisers' },
  mapNoOrgs: { ru: 'вы с ними не работаете', en: 'you do not work with them' },
  mapOrgsShort: { ru: 'орг.', en: "orgs" },
  mapCaption: {
    ru: 'Ширина квартала — оборот типа за месяц, зелёная заливка снизу — сколько из него прошло через вас. Рамка: зелёная — работаете, бирюзовая — виджет развёрнут, красный пунктир — организаторы уходят, тёмный квартал — тип, который вы не берёте.',
    en: 'Block width is the type’s monthly turnover; the green fill from below is how much of it went through you. The frame: green — you serve it, teal — the widget is deployed, red dashes — organisers are leaving, a dark block is a type you do not serve.',
  },  channelPanel: { ru: 'Каналы продаж: афиша и виджет', en: 'Sales channels: listings and widget' },
  moreHow: { ru: 'Как это устроено', en: 'How it works' },
  moreMoney: { ru: 'Куда уходят деньги с билета', en: 'Where the ticket money goes' },
  channelCaption: {
    ru: '<b>Билетный виджет</b> — это ваша продажа билетов, встроенная в сайт самого организатора: его домен, его брендинг, ваш движок под ними. На своей афише цену для покупателя назначаете вы и берёте с неё и сбор, и комиссию. На чужом сайте цену назначает хозяин сайта: сервисного сбора там нет, вам достаётся только ставка платформы — в разы меньше. Но без виджета организатор продаёт со своего сайта сам, и весь этот оборот идёт мимо вас целиком.<br><br><b>Кнопка не ставит виджет, а запускает переезд.</b> У каждого организатора уже что-то стоит — своё самописное или платформа конкурента, — и переезд стоит денег и месяцев: интеграция, перенос схем залов и абонементов, обучение кассиров, у крупных ещё и аванс под мероприятия. Скорость покупается <a class="jump" data-jump="lever:onboarding">бюджетом на подключения</a>, а тех, кто уже сидит у конкурента, переманить не выйдет вовсе.',
    en: 'A <b>ticketing widget</b> is your ticket sales embedded in the organiser\'s own site: their domain, their branding, your engine underneath. On your own listings you set the price the buyer sees and take both the fee and the commission from it. On someone else\'s site the owner sets the price: there is no service fee there, and all you get is the platform rate — several times less. But without the widget the organiser sells from their site on their own, and all of that turnover goes past you entirely.<br><br><b>The button does not install the widget, it starts the migration.</b> Every organiser already runs something — their own build or the rival\'s platform — and moving costs money and months: integration, porting seat maps and season tickets, training the box office, and an advance against events for the big ones. Speed is bought with the <a class="jump" data-jump="lever:onboarding">onboarding budget</a>, and those already sitting on the rival\'s platform cannot be won over at all.',
  },
  channelColType: { ru: 'Тип', en: 'Type' },
  needHigh: { ru: 'виджет необходим', en: 'widget essential' },
  needMid: { ru: 'виджет желателен', en: 'widget desirable' },
  needLow: { ru: 'обойдутся без виджета', en: 'fine without a widget' },
  channelColSplit: { ru: 'Куда уходят продажи', en: 'Where the sales go' },
  channelSplitLost: { ru: '{lost} мимо вас', en: '{lost} past you' },
  channelColMoney: { ru: 'Ваши деньги с билета', en: 'What a ticket earns you' },
  channelMoneyValue: { ru: '{market} с афиши', en: '{market} from listings' },
  channelMoneyWidget: { ru: '{widget} с виджета', en: '{widget} from the widget' },
  orgCardGmv: { ru: 'Оборот за месяц', en: 'Turnover per month' },
  orgCardMoney: { ru: 'С билета вам', en: 'You get per ticket' },
  orgCardSplit: { ru: 'Куда уходят продажи', en: 'Where sales go' },
  chanMarket: { ru: 'афиша {p}', en: 'listings {p}' },
  chanWidget: { ru: 'виджет {p}', en: 'widget {p}' },
  chanOwn: { ru: 'мимо {p}', en: 'past you {p}' },
  orgCardPrice: { ru: 'Переезд', en: 'Onboarding' },
  orgCardPriceValue: { ru: '{per} на организатора · {eta}', en: '{per} per organiser · {eta}' },
  orgCardPriceOff: { ru: 'не подключаем', en: 'not onboarding' },
  orgCardEta: { ru: 'все переедут за {n} мес', en: 'all move over in {n} mo' },
  orgCardEtaNever: { ru: 'при этом бюджете не переедут', en: 'at this budget they will not move' },
  channelOnboardSplit: {
    ru: 'бюджет переезда делится на {types} типа: {per} на организатора',
    en: 'the onboarding budget is split across {types} types: {per} per organiser',
  },
  channelOnboardNone: {
    ru: 'бюджет переезда сейчас никому не достаётся: тип не выбран',
    en: 'the onboarding budget goes nowhere: no type selected',
  },
  channelColMoneyNote: {
    ru: 'После эквайринга. Через афишу вы берёте сбор с покупателя и комиссию с организатора; через виджет — только ставку платформы, а банк берёт свою комиссию с обеих сумм одинаково. Поэтому виджет держится не на билете, а на абонплате и на том обороте, который иначе ушёл бы мимо вас совсем.',
    en: 'Net of card fees. Through your listings you take the buyer fee and the organiser commission; through the widget only the platform rate — and the bank takes its card fee off both alike. So the widget lives not off the ticket but off the subscription fee and off turnover that would otherwise pass you by entirely.',
  },
  channelColState: { ru: 'Переехали', en: 'Moved over' },
  channelOn: { ru: 'виджет стоит', en: 'widget installed' },
  channelOff: { ru: 'виджета нет', en: 'no widget' },
  channelConnect: { ru: 'Подключать этот тип', en: 'Onboard this type' },
  channelDisconnect: { ru: 'Перестать подключать', en: 'Stop onboarding' },
  channelQueued: { ru: 'подключаем', en: 'onboarding' },
  channelMoved: { ru: '{moved} из {total} переехали', en: '{moved} of {total} moved' },
  channelDisconnectWarn: { ru: 'Снятый виджет организаторы запоминают: часть уйдёт — и тем больше, чем больше их успело переехать. Обратный переезд мгновенный: выключить чужой сайт можно сразу, а вот включить — нет.', en: 'Organisers remember a widget being taken away: some will leave — and the more of them that had moved over, the worse it is. Going back is instant: switching off someone else\'s site takes a moment, switching it on does not.' },
  channelNoPlatform: { ru: 'Платформы пока нет — вложитесь в разработку, иначе виджет будет пустым обещанием.', en: 'There is no platform yet — invest in development, otherwise the widget is an empty promise.' },
  channelLevel: { ru: 'Уровень платформы {level}', en: 'Platform level {level}' },

  // --- Организаторы ---
  supplyPanel: { ru: 'Организаторы', en: 'Organisers' },
  supplyCaption: {
    ru: 'Заполняемость — то, что организатор видит своими глазами. Никакая комиссия не перебьёт пустой зал.',
    en: 'Fill rate is what the organiser sees with their own eyes. No commission beats an empty hall.',
  },
  supplyColCount: { ru: 'У вас', en: 'Yours' },
  supplyColFill: { ru: 'Зал заполнен на', en: 'Hall fill' },
  supplyColAppeal: { ru: 'Кого выбирают новые', en: 'Who new organisers pick' },
  supplyPickYou: { ru: 'вас {share}', en: 'you {share}' },
  supplyColGmv: { ru: 'Оборот', en: 'Turnover' },

  // --- Зрители ---
  audiencePanel: { ru: 'Зрители', en: 'Buyers' },
  audienceCaption: {
    ru: 'Афиша из одного жанра собирает одну аудиторию — и упирается в её размер, сколько ни трать на маркетинг.',
    en: 'Listings of a single genre gather a single audience — and hit its ceiling no matter how much marketing you buy.',
  },
  audienceColReach: { ru: 'Охват', en: 'Reach' },
  audienceColInterest: { ru: 'Афиша подходит', en: 'Listing fit' },
  audienceColConv: { ru: 'Конверсия', en: 'Conversion' },
  audienceColDemand: { ru: 'Спрос', en: 'Demand' },

  // --- Конкурент ---
  rivalPanel: { ru: 'Конкурент · {season}, месяц {month}', en: 'Rival · {season}, month {month}' },
  rivalTheirCommission: { ru: 'Комиссия с организатора:', en: 'Organiser commission:' },
  rivalTheirFee: { ru: 'Сбор с покупателя:', en: 'Buyer fee:' },
  rivalTheirReach: { ru: 'Охват:', en: 'Reach:' },
  rivalCheaper: { ru: '(на {gap} дешевле вашей)', en: '({gap} below yours)' },
  rivalDearer: { ru: '(на {gap} дороже вашей)', en: '({gap} above yours)' },
  rivalSame: { ru: '(как у вас)', en: '(same as yours)' },
  shareYou: { ru: 'Вы', en: 'You' },
  shareThem: { ru: 'Он', en: 'Rival' },
  shareBarHint: { ru: 'Доля рынка по числу организаторов', en: 'Market share by organiser count' },
  shareCaption: { ru: 'У вас {you} организаторов, у него {them}. Переток за месяц: {flow}.', en: 'You have {you} organisers, the rival has {them}. Net switching this month: {flow}.' },
  stanceGone: { ru: 'Ушёл с рынка', en: 'Left the market' },
  stanceGoneHint: { ru: 'Рынок ваш целиком. Теперь только от вас зависит, каким его увидят зрители.', en: 'The market is entirely yours. What buyers see on it is now up to you alone.' },
  rivalExclusive: { ru: 'Держит эксклюзив: {types}', en: 'Holds exclusives on: {types}' },

  // --- Эксклюзив ---
  exclusiveTitle: { ru: 'Предложение об эксклюзиве', en: 'An exclusivity offer' },
  exclusiveText: {
    ru: 'Организаторы категории «{type}» готовы работать только с вами {months} месяцев за аванс {advance}. Пока контракт действует, конкурент их не тронет — но и деньги вернутся не сразу.',
    en: 'Organisers in the “{type}” category will work with you exclusively for {months} months in exchange for a {advance} advance. While it lasts the rival cannot touch them — and the money comes back slowly.',
  },
  exclusiveAccept: { ru: 'Подписать', en: 'Sign' },
  exclusiveDecline: { ru: 'Отказаться', en: 'Decline' },
  exclusiveSigned: { ru: 'Эксклюзив подписан: {type} на {months} месяцев, аванс {advance}.', en: 'Exclusive signed: {type} for {months} months, advance {advance}.' },
  exclusiveMine: { ru: 'Ваш эксклюзив: {types}', en: 'Your exclusives: {types}' },

  // --- Совет акционеров ---
  boardPanel: { ru: 'Цель года', en: 'Goal of the year' },
  boardDone: { ru: 'Цели закончились — идёт последний отрезок партии.', en: 'No goals left — this is the final stretch.' },
  goalGmv: { ru: 'Оборот за месяц не ниже {target} к концу {year}-го года', en: 'Monthly turnover of at least {target} by the end of year {year}' },
  goalRevenue: { ru: 'Не менее {target} прибыльных месяцев за год при обороте от {floor}', en: 'At least {target} profitable months in the year, with turnover above {floor}' },
  goalShare: { ru: 'Доля рынка {target} при {floor} организаторах', en: 'Market share of {target} with {floor} organisers' },
  goalNow: { ru: 'сейчас {value}', en: 'now {value}' },
  goalYear: { ru: 'Год {year}', en: 'Year {year}' },
  goalPassed: { ru: 'выполнена', en: 'met' },
  goalFailed: { ru: 'провалена', en: 'missed' },

  // --- Кризисы ---
  crisisPanel: { ru: 'Кризис · месяц {months}', en: 'Crisis · month {months}' },
  crisisEscalates: { ru: 'Каждый месяц без решения делает его дороже.', en: 'Every month without a decision makes it more expensive.' },
  crisisCost: { ru: 'стоимость сейчас {cost}', en: 'costs {cost} now' },
  crisisFree: { ru: 'бесплатно', en: 'free' },

  // --- Инвестиции ---
  fundingTitle: { ru: 'Раунд инвестиций', en: 'Funding round' },
  fundingNote: { ru: 'Деньги можно взять в любой момент. Чем хуже дела, тем дороже они стоят: доля считается от текущей оценки.', en: 'You can raise at any time. The worse things are, the more it costs: the stake is priced off the current valuation.' },
  fundingRaise: { ru: 'Привлечь {amount}', en: 'Raise {amount}' },
  fundingDilution: { ru: 'отдадите {value} компании', en: 'you give up {value} of the company' },
  fundingLocked: { ru: 'Раунды открываются с {month}-го месяца.', en: 'Rounds open from month {month}.' },
  fundingStake: { ru: 'Ваша доля: {value}', en: 'Your stake: {value}' },

  // --- Графики ---
  chartMarket: { ru: 'Вы и конкурент', en: 'You and the rival' },
  chartMarketCaption: { ru: 'Рынок организаторов конечен. Расти можно, подключая свободных и переманивая чужих, — и второй способ работает быстрее.', en: 'The pool of organisers is finite. You grow by signing the unattached and taking the rival’s — and the second is faster.' },
  seriesYouOrgs: { ru: 'Ваши организаторы', en: 'Your organisers' },
  seriesThemOrgs: { ru: 'У конкурента', en: 'Rival’s' },

  chartChannels: { ru: 'Каналы', en: 'Channels' },
  chartChannelsCaption: { ru: 'Две нижние линии складываются в верхнюю. Чем больше оборота уходит на сайты организаторов, тем ниже ваша доля с билета.', en: 'The two lower lines add up to the top one. The more turnover moves to the organisers\' own sites, the less you earn per ticket.' },
  seriesGmv: { ru: 'Оборот всего', en: 'Total turnover' },
  seriesGmvMarket: { ru: 'Через афишу', en: 'Via listings' },
  seriesGmvPlatform: { ru: 'Через виджет на их сайтах', en: 'Via widget on their sites' },

  chartMoney: { ru: 'Деньги', en: 'Money' },
  chartMoneyCaption: { ru: 'Оборот — чужие деньги. Ваши — только выручка, и от неё ещё надо отнять эквайринг.', en: 'Turnover is other people’s money. Only the revenue is yours — and card fees still come out of it.' },
  seriesRevenue: { ru: 'Выручка', en: 'Revenue' },
  seriesContribution: { ru: 'Вклад', en: 'Contribution' },
  seriesProfit: { ru: 'Прибыль', en: 'Profit' },

  chartCash: { ru: 'Касса', en: 'Cash' },
  chartCashCaption: { ru: 'Ноль на этой линии заканчивает партию. Всё остальное — вопрос стратегии.', en: 'Zero on this line ends the game. Everything else is strategy.' },

  chartFill: { ru: 'Спрос и мест', en: 'Demand and seats' },
  chartFillCaption: { ru: 'Два независимых числа. Продаётся минимум из них, и организатор судит вас по тому, какая часть зала осталась пустой.', en: 'Two independent numbers. The smaller one sells, and the organiser judges you by how much of the hall stayed empty.' },
  seriesSeats: { ru: 'Мест выставлено', en: 'Seats listed' },
  seriesDemand: { ru: 'Спрос, билетов', en: 'Demand, tickets' },
  seriesSold: { ru: 'Продано', en: 'Sold' },

  chartTake: { ru: 'Доля оборота', en: 'Take rate' },
  chartTakeCaption: { ru: 'Сколько процентов оборота остаётся вам. Эквайринг вычитается из этого же числа, а не из оборота организатора.', en: 'What percentage of turnover stays with you. Card fees come out of this number, not out of the organiser’s.' },
  seriesTake: { ru: 'Ваша доля, %', en: 'Your take, %' },
  seriesAcq: { ru: 'Эквайринг, %', en: 'Card fees, %' },

  chartTrust: { ru: 'Доверие', en: 'Trust' },
  chartTrustCaption: { ru: 'Единственный актив билетного сервиса, который нельзя купить в тот месяц, когда он понадобился. Рядом нарисована конверсия: когда доверие проседает, она откликается первой.', en: 'The one asset a ticketing service cannot buy in the month it turns out to be needed. Conversion is drawn beside it: when trust sags, it is the first to follow.' },
  seriesTrust: { ru: 'Доверие, %', en: 'Trust, %' },
  seriesConv: { ru: 'Конверсия, %', en: 'Conversion, %' },

  chartAlgos: { ru: 'Алгоритмы', en: 'Algorithms' },
  chartAlgosCaption: { ru: 'Качество алгоритмов — это данные и команда одновременно. Одного мало.', en: 'Algorithm quality is data and team at once. Either alone is not enough.' },
  seriesQuality: { ru: 'Качество, %', en: 'Quality, %' },
  seriesData: { ru: 'Данные, %', en: 'Data, %' },
  seriesTeam: { ru: 'Команда, %', en: 'Team, %' },

  // --- Правая колонка ---
  tabUnit: { ru: 'Билет', en: 'Ticket' },
  tabPnl: { ru: 'P&L', en: 'P&L' },
  tabSides: { ru: 'Стороны', en: 'Both sides' },
  tabAlgos: { ru: 'Алгоритмы', en: 'Algorithms' },
  tabHelp: { ru: 'Справка', en: 'Guide' },

  unitIntro: { ru: 'Сколько остаётся с одного проданного билета. Средняя цена считается по вашей афише, а не по рынку.', en: 'What is left from one ticket sold. The average price is taken from your listings, not from the market.' },
  unitColItem: { ru: 'Статья', en: 'Line' },
  unitColPerTicket: { ru: 'На билет', en: 'Per ticket' },
  unitPrice: { ru: 'Цена билета (не ваша)', en: 'Ticket price (you do not set it)' },
  unitMarket: { ru: 'Через афишу: сбор + комиссия', en: 'Via listings: fee + commission' },
  unitPlatform: { ru: 'Через виджет на сайте организатора', en: 'Via widget on the organiser\'s site' },
  unitBlended: { ru: 'Ваша выручка с билета', en: 'Your revenue per ticket' },
  unitAcquiring: { ru: 'Эквайринг', en: 'Card fees' },
  unitSupport: { ru: 'Поддержка', en: 'Support' },
  unitContribution: { ru: 'Вклад с билета', en: 'Contribution per ticket' },
  unitBreakEven: { ru: 'Чтобы выйти в ноль, нужно {value} билетов в месяц.', en: 'To break even you need {value} tickets a month.' },

  pnlEmpty: { ru: 'Сыграйте месяц, чтобы увидеть отчёт.', en: 'Play a month to see the report.' },
  pnlRevenue: { ru: 'Выручка', en: 'Revenue' },
  pnlMarketplace: { ru: 'Афиша: сбор и комиссия', en: 'Listings: fee and commission' },
  pnlPlatform: { ru: 'Платформа: ставка', en: 'Platform: rate' },
  pnlSubscription: { ru: 'Платформа: абонплата', en: 'Platform: subscriptions' },
  pnlAcquiring: { ru: 'Эквайринг', en: 'Card fees' },
  pnlSupport: { ru: 'Поддержка', en: 'Support' },
  pnlContribution: { ru: 'Вклад', en: 'Contribution' },
  pnlMarketing: { ru: 'Маркетинг', en: 'Marketing' },
  pnlManagers: { ru: 'Аккаунт-менеджеры', en: 'Account managers' },
  pnlStaff: { ru: 'Штат: интеграции, финансы, юристы', en: 'Staff: integrations, finance, legal' },
  pnlPlatformDev: { ru: 'Разработка платформы', en: 'Platform development' },
  pnlPlatformSeats: { ru: 'Содержание подключённых', en: 'Running connected accounts' },
  pnlProduct: { ru: 'Продукт', en: 'Product' },
  pnlCapacity: { ru: 'Запас мощности', en: 'Capacity headroom' },
  pnlRnd: { ru: 'Команда данных', en: 'Data team' },
  pnlUpkeep: { ru: 'Содержание технологий', en: 'Technology upkeep' },
  pnlServers: { ru: 'Серверы и трафик', en: 'Servers and traffic' },
  pnlUpkeepNote: { ru: 'Содержание растёт от всего, что уже построено, серверы — от нагрузки. Обе статьи дорожают ровно тогда, когда дела идут хорошо.', en: 'Upkeep grows with everything already built, servers with the load. Both get more expensive exactly when things go well.' },
  pnlHq: { ru: 'Офис и администрация', en: 'Office and admin' },
  pnlProfit: { ru: 'Прибыль', en: 'Profit' },
  pnlOneOff: { ru: 'Разовые', en: 'One-offs' },
  pnlNet: { ru: 'С учётом разовых', en: 'After one-offs' },
  pnlGmvNote: { ru: 'Оборот за месяц {gmv} — это деньги зрителей, а не ваши. Ваша доля от него {take}.', en: 'Monthly turnover of {gmv} is buyers’ money, not yours. Your share of it is {take}.' },

  sidesSupply: { ru: 'Сторона предложения', en: 'Supply side' },
  sidesDemand: { ru: 'Сторона спроса', en: 'Demand side' },

  algoNoneYet: { ru: 'Пока не открыт ни один алгоритм. Первым станет доступен «{name}» — при качестве модели {value}. Качество растёт само от работы сервиса и от команды, отдельно платить за это не нужно.', en: 'No algorithm is available yet. The first to unlock is "{name}", at a model quality of {value}. Quality grows on its own from the service running and from the team; there is nothing extra to pay for it.' },
  algosIntro: { ru: 'Умные механики. Каждая что-то улучшает и что-то ломает — и почти каждая тем сильнее вредит, чем хуже данные.', en: 'The smart mechanics. Each improves something and breaks something — and almost every one hurts more the worse your data is.' },
  algosQuality: { ru: 'Качество алгоритмов {quality} · данные {data} · команда {team}', en: 'Algorithm quality {quality} · data {data} · team {team}' },
  algosLocked: { ru: 'Откроется при качестве {unlock}', en: 'Unlocks at quality {unlock}' },
  algosInstall: { ru: 'Внедрить за {cost}', en: 'Install for {cost}' },
  algosOn: { ru: 'включено', en: 'on' },
  algosOff: { ru: 'выключено', en: 'off' },
  algosNone: { ru: 'Ни один алгоритм пока не внедрён.', en: 'No algorithm has been installed yet.' },
  installNote: { ru: 'Внедрено: {names} — разовые {cost}.', en: 'Installed: {names} — a one-off {cost}.' },

  helpTitle: { ru: 'Что здесь происходит', en: 'What is going on here' },
  helpIntro: {
    ru: 'Вы управляете билетным сервисом. У него две стороны: организаторы дают афишу, зрители покупают билеты. Ни одна не приходит первой сама по себе — в этом вся задача.',
    en: 'You run a ticketing service. It has two sides: organisers provide the listings, buyers buy the tickets. Neither arrives first on its own — that is the whole problem.',
  },
  helpTake: {
    ru: '<b>Одна выручка, две стороны.</b> Сервисный сбор платит зритель, комиссию — организатор. Сумма может быть одинаковой, а последствия разные: сбор виден покупателю на оплате, комиссия — организатору в договоре.',
    en: '<b>One revenue, two sides.</b> The service fee is paid by the buyer, the commission by the organiser. The sum can be identical and the consequences are not: the buyer sees the fee at checkout, the organiser sees the commission in the contract.',
  },
  helpChannel: {
    ru: '<b>Конфликт каналов.</b> Билетный виджет на сайте организатора удерживает его от ухода, но продажи через него приносят в разы меньше — и эти билеты не появляются в вашей афише, а значит, не работают на ваш охват.',
    en: '<b>Channel conflict.</b> A ticketing widget on the organiser\'s own site keeps them from leaving, but sales through it earn several times less — and those tickets never appear in your listings, so they do not build your reach.',
  },
  helpGmv: {
    ru: '<b>Оборот и выручка — разные числа.</b> Через вас проходят миллиарды, ваши из них — проценты. Эквайринг вычитается из этих процентов, а не из оборота.',
    en: '<b>Turnover and revenue are different numbers.</b> Vast sums pass through you; only a few percent are yours. Card fees come out of those percentages, not out of the turnover.',
  },
  helpTrust: {
    ru: '<b>Доверие.</b> Перекупщики, упавший сайт и скрытый сбор бьют по одному счёту. Оборот при этом держится — и в этом ловушка: цифры выглядят нормально ровно до месяца, когда становится поздно.',
    en: '<b>Trust.</b> Resellers, an outage and a hidden fee all hit the same account. Turnover holds up meanwhile — and that is the trap: the numbers look fine right up to the month it is too late.',
  },
  helpSeeds: { ru: 'Партия детерминирована: одинаковый код партии даёт одинаковый мир. Это нужно, чтобы вся группа играла в один и тот же город.', en: 'A game is deterministic: the same game code gives the same world. That way a whole class plays the same city.' },

  // --- Финал ---
  overTitle: { ru: 'Партия окончена', en: 'The game is over' },
  overBankrupt: { ru: 'Деньги кончились на {month}-м месяце.', en: 'The money ran out in month {month}.' },
  overSold: { ru: 'Деньги кончились на {month}-м месяце. Совет продал сервис: 28% оценки минус долги — ваша доля остатка {value}. Продажа за долги — не ноль, но и не победа.', en: 'The money ran out in month {month}. The board sold the service: 28% of the valuation minus the debts — your share of the remainder is {value}. A distressed sale is not zero, but it is not a win either.' },
  overFinished: { ru: 'Три года позади.', en: 'Three years are behind you.' },
  overStats: {
    ru: 'Оценка компании {valuation}, ваша доля {equity} — это {value}. Организаторов {orgs}, доля рынка {share}, оборот {gmv}, доверие {trust}.',
    en: 'Valuation {valuation}, your stake {equity} — that is {value}. Organisers {orgs}, market share {share}, turnover {gmv}, trust {trust}.',
  },
  overGoals: { ru: 'Цели: {list}', en: 'Goals: {list}' },
  overAgain: { ru: 'Сыграть заново', en: 'Play again' },
  overQuestions: { ru: '<b>Вопросы для разбора:</b> кто на самом деле ваш клиент — зритель или организатор? Какая часть оборота держалась на одном крупном промоутере? Что стоило дороже — уступки организаторам или потерянное доверие зрителей?', en: '<b>Questions for the debrief:</b> who is your real customer — the buyer or the organiser? How much of the turnover rested on one large promoter? Which cost more — concessions to organisers or the buyers’ lost trust?' },

  // --- персональный разбор: правила по телеметрии партии (аудит 2026-08) ---
  debriefTitle: { ru: 'Разбор партии', en: 'Game debrief' },
  debriefNote: {
    ru: 'Что игра заметила в вашей партии — и сколько это стоило. Цены — из цифр самой партии и контрольных партий.',
    en: 'What the game noticed in your run — and what it cost. The costs shown come from the run’s own numbers and from control runs.',
  },
  debriefClean: {
    ru: 'Системных промахов не нашлось: авансы возвращались, боты не хозяйничали, касса держала подушку. Сильная партия.',
    en: 'No systematic misses found: advances came back, bots never took over, cash kept its cushion. A strong run.',
  },
  debriefAdvances: {
    ru: 'Авансы организаторам списаны на {lost} — вернулось только {back}. Ставка на хиты без запаса: каждый списанный аванс — это чужой концерт, оплаченный вашей кассой.',
    en: 'Organiser advances written off: {lost} — only {back} came back. Betting on hits without a cushion: every written-off advance is someone else’s show paid from your cash.',
  },
  debriefBots: {
    ru: 'Перекупщики (боты) держали 18%+ продаж {n} месяцев, а антибот-фильтр стоял на нуле. Доверие зрителей — это спрос следующих месяцев: в здоровой партии доля перекупщиков не поднимается выше 15%.',
    en: 'Resellers (bots) held 18%+ of sales for {n} months while the anti-bot filter sat at zero. Buyer trust is the coming months’ demand: in a healthy run the reseller share never tops 15%.',
  },
  debriefThinCash: {
    ru: 'Касса жила ниже месяца расходов {n} месяцев при убыточной операционке. Любой шок в такой момент — продажа за долги: она возвращает лишь 28% оценки.',
    en: 'Cash sat below one month of costs for {n} months while operations ran at a loss. Any shock at such a moment means a distressed sale — it returns only 28% of the valuation.',
  },
  debriefRanDry: {
    ru: 'Касса кончилась в месяце {m}: продажа за долги возвращает лишь 28% оценки. Подушка и ранний раунд стоят дешевле, чем спасение.',
    en: 'Cash ran out in month {m}: a distressed sale returns only 28% of the valuation. A cushion and an early round cost less than a rescue.',
  },
  gameOverCharts: { ru: 'Посмотреть графики', en: 'Look at the charts' },
  // --- Развилка перед смертью и разбор краха ---
  deathTitle: { ru: '⚠️ Деньги на исходе', en: '⚠️ Running out of money' },
  deathText: { ru: 'В кассе {cash}, за прошлый месяц сожгли {burn}. Таким темпом денег хватит примерно на {runway}. Раунд ещё можно поднять — но чем ближе касса к нулю, тем хуже условия. Это предупреждение показывается один раз.', en: 'You have {cash} in the bank; last month burned {burn}. At this pace the money lasts about {runway}. A round can still be raised — but the closer the balance is to zero, the worse the terms. You will only see this warning once.' },
  deathRunway: { ru: '{n} мес.', en: '{n} mo' },
  deathRaise: { ru: 'Поднять {amount} (доля −{dilution})', en: 'Raise {amount} (stake −{dilution})' },
  deathIgnore: { ru: 'Продолжить как есть', en: 'Carry on as is' },
  deathRaised: { ru: 'Раунд закрыт: +{amount} в кассу, доля снизилась до {equity}.', en: 'Round closed: +{amount} in the bank, stake now {equity}.' },
  deathWaterfall: { ru: 'Последние месяцы: куда ушли деньги', en: 'The final months: where the money went' },
  wfRevenue: { ru: 'Выручка', en: 'Revenue' },
  wfCosts: { ru: 'Расходы', en: 'Costs' },
  wfProfit: { ru: 'Итог месяца', en: 'Month net' },
  wfCash: { ru: 'Касса на конец', en: 'Cash at end' },
  wfTurn: { ru: 'мес. {n}', en: 'mo {n}' },
  // --- Код партии и таблица рекордов ---
  scoreRaised: { ru: 'Привлечено', en: 'Raised' },
  scoreCash: { ru: 'Касса', en: 'Cash' },
  totalsTitle: { ru: 'Вся партия: куда пришли и ушли деньги', en: 'The whole game: where the money came from and went' },
  csvButton: { ru: 'Скачать CSV', en: 'Download CSV' },
  csvTurn: { ru: 'месяц', en: 'month' },
  finalShareTitle: { ru: 'Поделиться, отправить в таблицу, скачать', en: 'Share, submit to the leaderboard, download' },
  finalNextTitle: { ru: 'Куда пойти дальше', en: 'Where to go next' },
  resultNote: { ru: 'Скопируйте и отправьте преподавателю: в строке зашиты код партии, счёт и контрольная сумма. В НОВОГРАД этот финал переходит сам — строка нужна, только если продолжать на другом устройстве.', en: 'Copy it and send it to your teacher: the string carries the game code, the score and a checksum. NOVOGRAD picks this result up on its own — you only need the string to continue on another device.' },
  resultCopy: { ru: 'Скопировать', en: 'Copy' },
  resultCopied: { ru: 'Строка результата скопирована.', en: 'Result string copied.' },
  recordsTitle: { ru: 'Ваши лучшие партии на этом устройстве', en: 'Your best games on this device' },
  recordsDate: { ru: 'Дата', en: 'Date' },
  recordsCode: { ru: 'Код партии', en: 'Game code' },
  recordsScore: { ru: 'Итог', en: 'Score' },
  recordsOutcome: { ru: 'Исход', en: 'Outcome' },
  recordsOutcomeFinished: { ru: 'финиш', en: 'finished' },
  recordsOutcomeBankrupt: { ru: 'банкрот', en: 'bankrupt' },
  recordsOutcomeSold: { ru: 'продана', en: 'sold' },
  recordsYou: { ru: '← эта партия', en: '← this game' },
  seedLabel: { ru: 'Код партии (необязательно)', en: 'Game code (optional)' },
  seedFold: { ru: 'Код партии', en: 'Game code' },
  seedPlaceholder: { ru: 'например, урок-7б', en: 'e.g. class-7b' },
  seedWeeklyNote: { ru: 'Подставлен город недели — общий для всех, кто начнёт партию на этой неделе: одинаковый город делает сравнение честным. Хотите случайный — просто сотрите код.', en: 'The city of the week is filled in — shared by everyone starting a game this week: an identical city keeps the comparison fair. Want a random one? Just clear the code.' },
  seedNote: { ru: 'Одинаковый код — одинаковый город у всех, кто его ввёл. Пустое поле — случайный.', en: 'The same code gives everyone the same city. Empty means random.' },
  welcomeBest: { ru: 'Ваш лучший результат на этом устройстве: {score}.', en: 'Your best result on this device: {score}.' },
  // --- Мировая таблица результатов (общие ключи shared/leaderboard.js) ---
  lbSeedPlaceholder: { ru: 'Фильтр по коду партии: один город — одна таблица', en: 'Filter by game code: one city, one table' },
  lbSeedMine: { ru: 'Мой город', en: 'My city' },
  lbEmptySeed: { ru: 'С этим кодом партии в топе пока пусто.', en: 'No entries with this game code yet.' },
  lbTabWorld: { ru: '🌍 Мировая', en: '🌍 World' },
  lbTabWeek: { ru: '🏆 Топ недели', en: '🏆 This week' },
  lbWeekEmpty: { ru: 'На этой неделе ещё никто не доиграл — будьте первым.', en: 'Nobody has finished this week yet — be the first.' },
  lbTitle: { ru: 'Мировая таблица', en: 'World leaderboard' },
  lbLoading: { ru: 'Загружаю таблицу…', en: 'Loading the leaderboard…' },
  lbEmpty: { ru: 'Пока пусто — ваш результат может стать первым.', en: 'Empty so far — yours could be the first.' },
  lbColPlayer: { ru: 'Игрок', en: 'Player' },
  lbColScore: { ru: 'Счёт', en: 'Score' },
  lbColCode: { ru: 'Код партии', en: 'Game code' },
  lbColDate: { ru: 'Дата', en: 'Date' },
  lbNamePlaceholder: { ru: 'Ваше имя или ник', en: 'Your name or nickname' },
  lbSubmit: { ru: 'Отправить результат', en: 'Submit result' },
  lbConsent: { ru: 'Отправляются только имя и строка результата: игра, версия, код партии, счёт и ходы.', en: 'Only your name and the result string are sent: game, version, game code, score and turns.' },
  lbNameNeeded: { ru: 'Напишите имя: таблице нужен подписанный результат.', en: 'Enter a name: the leaderboard needs a name on the result.' },
  lbSending: { ru: 'Отправляю…', en: 'Sending…' },
  lbSent: { ru: 'Готово: вы на {rank}-м месте из {total}.', en: 'Done: you are #{rank} of {total}.' },
  lbYou: { ru: '(вы)', en: '(you)' },
  btnHome: { ru: 'Игры', en: 'Games' },
  btnHomeTitle: { ru: 'К списку игр', en: 'Back to all games' },
  lbInvite: { ru: 'Впишите свой результат — таблица общая для всех, кто играет по ссылке.', en: 'Add your result — the leaderboard is shared by everyone playing online.' },
  lbYourPlace: { ru: 'Ваш лучший отправленный результат: {score} — место {rank} из {total} на момент отправки.', en: 'Your best submitted result: {score} — rank {rank} of {total} at submission time.' },
  lbAlreadySent: { ru: 'Результат этой партии уже в таблице.', en: 'This game’s result is already on the leaderboard.' },
  lbError: { ru: 'Таблица сейчас недоступна. Результат можно отправить позже, пока открыт этот экран.', en: 'The leaderboard is unreachable right now. You can submit later while this screen is open.' },
  // --- Оговорка о числах: одинаковая во всех трёх играх ---
  welcomeNumbers: { ru: '<b>О числах.</b> Все числа условные, подобранные для играбельности, — не бенчмарки и не данные реальных компаний; оценивать по игре настоящий бизнес нельзя.', en: '<b>About the numbers.</b> All numbers are notional, chosen for playability — not benchmarks, not real companies’ data; the game is not a way to judge a real business.' },
  footNumbers: { ru: 'Числа в модели условные, не отраслевые бенчмарки: игра иллюстрирует механику связей, а не величины.', en: 'The numbers in the model are notional, not industry benchmarks: the game illustrates the mechanics of the relationships, not the magnitudes.' },
  helpSeedCode: { ru: 'Код этой партии: <b>{seed}</b> — введите его на экране приветствия, чтобы сыграть тот же город ещё раз.', en: 'This game’s code: <b>{seed}</b> — enter it on the welcome screen to play the same city again.' },
  // --- Дневник решений на графике ---
  chartChangesTitle: { ru: 'Пунктир — ваши решения.', en: 'Dashed lines are your decisions.' },
  chartChangeItem: { ru: 'мес. {turn}: {what}', en: 'mo {turn}: {what}' },
  chartChangePlatform: { ru: 'типы площадок платформы', en: 'platform venue types' },
  reportDelta: { ru: 'К прошлому месяцу: оборот {gmv}, прибыль {profit}, касса {cash}.', en: 'Versus last month: turnover {gmv}, profit {profit}, cash {cash}.' },
  fundingRunway: { ru: 'При темпе прошлого месяца кассы хватит примерно на {n} мес. Раунд дешевле поднимать заранее, а не у нуля.', en: 'At last month’s pace the cash lasts about {n} months. A round is cheaper raised early, not at zero.' },
  gradeBankrupt: { ru: 'Банкротство. Оборот в билетном бизнесе растёт легко — платит по счетам выручка.', en: 'Bankruptcy. Turnover in ticketing grows easily — it is revenue that pays the bills.' },
  gradeSold: { ru: 'Продана за долги. Партнёрская сеть чего-то стоила даже в спешке.', en: 'Distressed sale. The partner network was worth something even in a hurry.' },
  gradeExcellent: { ru: 'Отличный результат: рынок ваш, и он вам ещё и платит.', en: 'An excellent result: the market is yours, and it pays you too.' },
  gradeSolid: { ru: 'Крепкий результат. Бизнес стоит на ногах и растёт.', en: 'A solid result. The business stands on its own and grows.' },
  gradeSurvived: { ru: 'Вы выжили. Но оборот так и не стал выручкой.', en: 'You survived. But turnover never turned into revenue.' },
  gradeModest: { ru: 'Скромно. Рынок остался за конкурентом.', en: 'Modest. The market stayed with the rival.' },

  eventChoiceNeeded: { ru: 'Сначала выберите вариант в событии', en: 'Choose an option in the event first' },

  seasonAutumn: { ru: 'осень', en: 'autumn' },
  seasonWinter: { ru: 'зима', en: 'winter' },
  seasonSpring: { ru: 'весна', en: 'spring' },
  seasonSummer: { ru: 'лето', en: 'summer' },

  hitTitle: { ru: 'Хит месяца: {name}', en: 'Hit of the month: {name}' },

  // --- Новости месяца ---
  todoCapacityUrgentTitle: { ru: 'Запаса мощности нет, а в город едет: {name}', en: 'No capacity headroom, and this is coming to town: {name}' },
  todoCapacityUrgentText: { ru: 'Тур уже объявлен — значит в день старта продаж на сайт придут все сразу. Купить запас можно только заранее: в тот самый день он не появится.', en: 'The tour is announced, so on the on-sale day everyone arrives at once. Headroom can only be bought in advance — it will not appear on the day itself.' },
  newsAdvance: { ru: '<b>Аванс возвращается: {back} за месяц.</b> Организатору осталось отдать {left} — это ваши деньги, но пока не ваша выручка: в прибыли их нет, в кассе есть.', en: '<b>The advance is coming back: {back} this month.</b> The organiser still owes {left} — your money, but not yet your revenue: it is in the cash, not in the profit.' },
  newsAdvanceLost: { ru: '<b>Списано {lost} невозвращённого аванса.</b> Срок вышел, а зал столько не собрал. Аванс — это не плата за права, а деньги в долг под чужие продажи: вернуть их обязана выручка, которой может и не быть.', en: '<b>{lost} of the advance written off.</b> The term ran out and the halls never sold that much. An advance is not a fee for rights but money lent against someone else\'s sales: it is repaid by revenue that may simply not appear.' },
  newsPanel: { ru: 'Что в городе', en: 'What is on in town' },
  newsEmpty: { ru: 'Месяц без событий: обычная афиша, обычные залы. Такие месяцы и кормят — на них видно настоящую экономику сервиса, без всплесков.', en: 'A month with nothing in it: ordinary listings, ordinary halls. These are the months that feed you — they show the real economics of the service, without the spikes.' },
  newsHitNext: { ru: '<b>В следующем месяце: {name}.</b> {note} Спрос подскочит, а вместе с ним нагрузка на сайт и интерес перекупщиков. Готовиться надо сейчас: <a class="jump" data-jump="lever:capacityTech">запас мощности</a> покупается заранее, в день старта продаж уже поздно.', en: '<b>Next month: {name}.</b> {note} Demand will spike, and so will the load on the site and the interest of resellers. Prepare now: <a class="jump" data-jump="lever:capacityTech">capacity headroom</a> is bought in advance — on the on-sale day it is too late.' },
  newsHitNow: { ru: '<b>{name} — сейчас.</b> {note}', en: '<b>{name} — this month.</b> {note}' },
  newsHitQuiet: { ru: 'На следующий месяц ничего крупного не заявлено. Спокойный месяц — хорошее время что-то поменять и увидеть эффект без помех.', en: 'Nothing big is announced for next month. A quiet month is a good time to change something and see the effect without noise.' },
  newsSeasonAutumn: { ru: '<b>Сентябрь: открывается театральный сезон.</b> Театры и филармонии выкатывают афишу на год вперёд — их проще подключить именно сейчас.', en: '<b>September: the theatre season opens.</b> Theatres and concert halls publish a year of listings at once — this is when they are easiest to sign.' },
  newsSeasonSummer: { ru: '<b>Лето: театры закрыты, стадионы полны.</b> Половина обычной афиши исчезает, зато у спорта и фестивалей это лучшие месяцы года.', en: '<b>Summer: theatres are dark, stadiums are full.</b> Half the usual listings vanish, but for sport and festivals these are the best months of the year.' },
  newsSeasonWinter: { ru: '<b>Декабрь и январь: ёлки и корпоративы.</b> Спрос высокий, но короткий — и почти весь приходится на две недели.', en: '<b>December and January: holiday shows.</b> Demand is high but short, and almost all of it lands in two weeks.' },
  newsRivalStance: { ru: '<b>Конкурент меняет тактику: {stance}.</b> {note}', en: '<b>The rival changes tack: {stance}.</b> {note}' },
  newsResellers: { ru: '<b>Перекупщики забрали {share} билетов.</b> Оборот от этого только вырос — а доверие зрителей падает, и это увидят не сразу.', en: '<b>Resellers took {share} of the tickets.</b> Turnover only went up — and buyer trust is falling, which nobody notices at once.' },
  newsOutage: { ru: '<b>Сайт не выдержал старта продаж:</b> потеряно {share} спроса. Запас мощности держат весь год ради одного такого дня.', en: '<b>The site went down at the on-sale:</b> {share} of demand lost. Capacity headroom is held all year for a single day like this one.' },
  newsGrowth: { ru: '<b>Организаторы за месяц: пришли {joined}, ушли {left}.</b> {verdict}', en: '<b>{joined} organisers joined this month, {left} left.</b> {verdict}' },
  newsGrowthGood: { ru: 'Приток обгоняет отток — рынок идёт к вам.', en: 'Inflow beats outflow — the market is coming your way.' },
  newsGrowthEven: { ru: 'Сколько пришло, столько и ушло: база стоит на месте. Это не покой, а равновесие двух сильных потоков.', en: 'As many joined as left: the base is flat. That is not calm, it is two strong flows cancelling out.' },
  newsGrowthBad: { ru: 'Уходит больше, чем приходит. Смотрите на заполняемость залов и на то, сколько вы забираете.', en: 'More are leaving than arriving. Look at hall fill and at how much you take.' },
  unitTickets: { ru: 'билетов', en: 'tickets' },
  unitSeats: { ru: 'мест', en: 'seats' },
  unitOrgs: { ru: 'организаторов', en: 'organisers' },
  metaConglomerate: { ru: 'Конгломерат Новограда.', en: 'The Novograd Conglomerate.' },
  metaConglomerateText: {
    ru: 'Ваша экосистема в НОВОГРАДЕ состоялась — города-побратимы открыты. Сыграйте партию с одним из кодов: {seeds}. Награда символическая: экономика зачётных партий не меняется.',
    en: 'Your NOVOGRAD ecosystem made it — the twin cities are open. Play a game with one of these codes: {seeds}. The reward is symbolic: ranked games’ economics stay untouched.',
  },
  metaReturnTitle: { ru: 'Вы вернулись из экосистемы', en: 'You are back from the ecosystem' },
  metaReturnText: {
    ru: 'В НОВОГРАДЕ финал этой игры становится стартовым активом холдинга: ваша база, ARPU и казна там — это то, что вы заработали здесь. Ваш лучший финал здесь — {best}. Следующая ступень наследия открывается с {target}. На эту партию правило не влияет: наследие работает в НОВОГРАДЕ, а не здесь.',
    en: 'In NOVOGRAD this game’s final result becomes the holding’s starting asset: the base, ARPU and treasury there are what you earned here. Your best result here is {best}. The next legacy step opens at {target}. It does not affect this game: the legacy works in NOVOGRAD, not here.',
  },
  metaReturnNone: {
    ru: 'В НОВОГРАДЕ финал этой игры становится стартовым активом холдинга: ваша база, ARPU и казна там — это то, что вы заработаете здесь. Доигранных финалов здесь у вас пока нет — первая ступень наследия открывается с {target}. На эту партию правило не влияет: наследие работает в НОВОГРАДЕ, а не здесь.',
    en: 'In NOVOGRAD this game’s final result becomes the holding’s starting asset: the base, ARPU and treasury there are what you earn here. You have no completed runs here yet — the first legacy step opens at {target}. It does not affect this game: the legacy works in NOVOGRAD, not here.',
  },
  metaReturnMaxed: {
    ru: 'Ваш финал этой игры уже даёт наследию максимум — выше шкала переноса не идёт: рекордная прошлая партия не должна решать новую. Возвращайтесь сюда за самой игрой, а не за бонусом.',
    en: 'Your best result here already gives the legacy its maximum — the carry-over scale goes no higher: a record past run should not decide a new one. Come back for the game itself, not the bonus.',
  },
  metaContinueTitle: { ru: 'Есть продолжение', en: 'There is a sequel' },
  metaContinueText: {
    ru: 'НОВОГРАД — четвёртая игра серии. Там вы управляете уже не одним сервисом, а холдингом: такси, е-ком, общая подписка. Ваша «БИЛЕТВИЛЬ» станет его стартовым активом — с той базой и кассой, что вы заработали здесь.',
    en: 'NOVOGRAD is the fourth game in the series. There you run a holding rather than a single service: taxi, e-commerce, one subscription across them all. Your TICKETGRAD becomes its starting asset — with the customer base and cash you earned here.',
  },
  metaContinueLink: { ru: 'Играть в НОВОГРАД →', en: 'Play NOVOGRAD →' },

  // --------------------------------------------------------------------------
  // Карточка «поделиться»: картинка для ленты, собирается из истории партии
  shareBtn: { ru: 'Поделиться картинкой', en: 'Share as image' },
  tryOthersText: { ru: 'Или смените индустрию — те же законы экономики, другой бизнес:', en: 'Or switch industries — the same economics, a different business:' },
  tryOthersA: { ru: '🛵 НОВОЕДА — доставка', en: '🛵 NOVOEDA — delivery' },
  tryOthersB: { ru: '🎬 КИНОРЕКА — стриминг', en: '🎬 KINOREKA — streaming' },
  shareNote: { ru: 'Карточка результата: график партии и итог одной картинкой — для чата или сторис. Нажмите на превью, чтобы рассмотреть.', en: 'Your result card: the run and the score in one image — for chats or stories. Tap the preview to see it full-size.' },
  shareClose: { ru: 'Закрыть', en: 'Close' },
  shareSub: { ru: 'браузерный симулятор экономики', en: 'a browser economics sim' },
  shareHookWin: { ru: 'Я три года строил билетный сервис.', en: 'I spent three years building a ticketing service.' },
  shareHookWinAsk: { ru: 'Обойдёте меня?', en: 'Think you can beat me?' },
  shareHookDead: { ru: 'Мой билетный сервис утонул за {n} месяцев.', en: 'My ticketing service sank in {n} months.' },
  shareHookDeadAsk: { ru: 'Покажете, как надо?', en: 'Show me how it is done?' },
  shareLegendPlus: { ru: 'месяц в плюс', en: 'month in profit' },
  shareLegendZero: { ru: 'в ноль', en: 'break-even' },
  shareLegendMinus: { ru: 'в минус', en: 'at a loss' },
  shareLegendPick: { ru: 'самое дорогое решение', en: 'the priciest decision' },
  shareOutcome: { ru: 'оценка компании через три года', en: 'company value after three years' },
  shareCta: { ru: 'Принять вызов →', en: 'Take the challenge →' },
  shareUrlNote: { ru: 'бесплатно, без регистрации, прямо в браузере', en: 'free, no sign-up, right in the browser' },
  shareSaved: { ru: 'Картинка сохранена.', en: 'Image saved.' },
  shareLinkCopied: { ru: 'Ссылка на игры уже в буфере — вставьте её в подпись, и она будет кликабельной.', en: 'The game link is in your clipboard — paste it into the caption to make it clickable.' },
};
