// ============================================================================
// Строки интерфейса игры «КИНОПОТОК». Пары { ru, en }.
// Регистрируются в ядре локализации вызовом setStrings() при старте.
// ============================================================================

export const STRINGS = {
  // --- шапка ---
  brandTitle: { ru: 'КИНОПОТОК', en: 'KINOPOTOK' },
  brandSub: { ru: 'экономический симулятор онлайн-кинотеатра', en: 'streaming service economics simulator' },
  btnRestart: { ru: 'Заново', en: 'Restart' },
  btnHelpTitle: { ru: 'Как играть', en: 'How to play' },
  btnNext: { ru: 'Прожить месяц {month} →', en: 'Run month {month} →' },
  btnResults: { ru: 'Итоги партии', en: 'Final results' },
  langToggle: { ru: 'EN', en: 'RU' },
  langTitle: { ru: 'Switch to English', en: 'Переключить на русский' },

  // --- KPI ---
  kpiMonth: { ru: 'Месяц', en: 'Month' },
  kpiMonthEvent: { ru: '⚡ событие', en: '⚡ event' },
  kpiMonthCalm: { ru: 'обычный месяц', en: 'a quiet month' },
  kpiCash: { ru: 'Касса', en: 'Cash' },
  kpiCashOut: { ru: 'деньги кончились', en: 'out of money' },
  kpiRunway: { ru: 'хватит на {months} мес.', en: '{months} months of runway' },
  kpiProfitable: { ru: 'операционно прибыльны', en: 'operationally profitable' },
  kpiSubs: { ru: 'Подписчики', en: 'Subscribers' },
  kpiSubsSub: { ru: '{premium} платных · {ads} с рекламой', en: '{premium} ad-free · {ads} on ads' },
  kpiRevenue: { ru: 'Выручка / мес', en: 'Revenue / mo' },
  kpiRevenueSub: { ru: 'ARPU {value}', en: 'ARPU {value}' },
  kpiProfit: { ru: 'Прибыль / мес', en: 'Profit / mo' },
  kpiProfitSub: { ru: 'вклад {value}', en: 'contribution {value}' },
  kpiChurn: { ru: 'Отток', en: 'Churn' },
  kpiChurnSub: { ru: 'жизнь подписки {months} мес.', en: 'subscription lasts {months} mo.' },
  kpiHours: { ru: 'Часов на подписчика', en: 'Hours per subscriber' },
  kpiHoursSub: { ru: 'трафик {value}', en: 'bandwidth {value}' },
  kpiEquity: { ru: 'Оценка × доля', en: 'Valuation × stake' },
  kpiEquitySub: { ru: 'ваша доля {value}', en: 'your stake {value}' },
  kpiStart: { ru: 'Старт', en: 'Start' },
  kpiStartSub: { ru: 'деньги инвестора, 100% ваши', en: 'investor money, 100% yours' },

  // --- панели ---
  panelLevers: { ru: 'Рычаги управления', en: 'Business levers' },
  panelStudio: { ru: 'Студия и производство', en: 'Studio and production' },
  panelAlgos: { ru: 'Алгоритмы и данные', en: 'Algorithms and data' },
  panelFunding: { ru: 'Финансирование', en: 'Funding' },
  panelBoard: { ru: 'Совет директоров', en: 'The board' },
  jumpGo: { ru: 'перейти →', en: 'go there →' },
  alertsMore: { ru: 'И ещё {count} наблюдений — они видны во вкладках справа.', en: 'And {count} more observations — they are in the tabs on the right.' },
  panelPartners: { ru: 'Партнёрства и бандлы', en: 'Partnerships and bundles' },
  partnerSummary: { ru: 'опт — {share} базы · ARPU {wholesale} ₽ против {retail} ₽ в рознице', en: 'wholesale is {share} of the base · ARPU ₽{wholesale} against ₽{retail} retail' },
  partnerMonthsLeft: { ru: 'осталось {months} мес.', en: '{months} mo. left' },
  partnerDealMeta: { ru: '{subs} подписчиков · {arpu} ₽ с человека ({share} от прайса)', en: '{subs} subscribers · ₽{arpu} each ({share} of list price)' },
  partnerLockedRate: { ru: 'Ставка зафиксирована при подписании: {signed} ₽ при текущем прайсе {list} ₽. Повышение цены на этот контракт не действует.', en: 'The rate was fixed at signing: ₽{signed} against a current list price of ₽{list}. A price rise does not apply to this contract.' },
  partnerEnding: { ru: 'Контракт кончается — эти люди уйдут разом, а не по одному.', en: 'The contract is ending — these people will leave all at once, not one by one.' },
  partnerTerm: { ru: 'контракт {months} мес.', en: '{months}-month contract' },
  partnerReach: { ru: 'приводит до {reach}/мес', en: 'brings up to {reach}/mo' },
  partnerShareOf: { ru: 'вам {share} прайса = {arpu} ₽', en: 'you keep {share} of list = ₽{arpu}' },
  partnerHours: { ru: 'смотрят {value} от обычного', en: 'they watch {value} of normal' },
  partnerChurnMult: { ru: 'отток {value} от обычного', en: 'churn {value} of normal' },
  partnerSetup: { ru: 'подключение {fee} разово', en: 'setup {fee} one-off' },
  partnerMonthly: { ru: '{fee} в месяц', en: '{fee} a month' },
  partnerExclusive: { ru: 'эксклюзив: другие операторы будут закрыты', en: 'exclusive: other operators will be locked out' },
  partnerSign: { ru: 'Подписать контракт', en: 'Sign the contract' },
  partnerSignDetail: { ru: 'До {subs} новых в месяц по {arpu} ₽ вместо {retail} ₽. Быстрый объём вместо выручки с человека.', en: 'Up to {subs} new a month at ₽{arpu} instead of ₽{retail}. Volume fast, revenue per head slow.' },
  partnerDecline: { ru: 'Отказаться', en: 'Decline' },
  partnerDeclineDetail: { ru: 'Растём розницей: дороже и медленнее, зато это ваши подписчики и ваша цена.', en: 'Grow retail instead: slower and dearer, but they are your subscribers at your price.' },
  todoPartnerTitle: { ru: 'Предложение о партнёрстве: {name}', en: 'A partnership offer: {name}' },
  todoPartnerText: { ru: 'Оптовый канал приводит людей быстрее маркетинга, но каждый из них стоит меньше и смотрит меньше. Ответить нужно в этом месяце.', en: 'The wholesale channel brings people faster than marketing, but each of them is worth less and watches less. Answer this month.' },
  todoPartnerEndTitle: { ru: 'Контрактов на исходе: {count}', en: '{count} contracts running out' },
  todoPartnerEndText: { ru: 'Когда контракт кончится, {subs} подписчиков уйдут почти разом. К этому моменту рознице должно быть чем их заменить.', en: 'When the contract ends, {subs} subscribers leave almost at once. By then retail needs something to replace them with.' },

  // --- Разрыв цены (постоянный блок у ползунка) ---
  gapList: { ru: 'прайс', en: 'list' },
  gapPaid: { ru: 'платят', en: 'paid' },
  gapNone: { ru: 'совпадает', en: 'aligned' },
  gapAligned: { ru: 'База уже платит по прайсу — повышать нечего.', en: 'The base already pays list price — nothing to raise.' },
  gapAnnual: { ru: 'Из них {subs} на годовом тарифе: их повышение не коснётся.', en: 'Of these {subs} are on annual plans: a rise will not touch them.' },
  gapNoData: { ru: 'Разрыв появится, когда у сервиса будет база.', en: 'The gap appears once the service has a base.' },

  panelSlate: { ru: 'Производство и релизы', en: 'Production and releases' },
  panelTurn: { ru: 'Ход месяца {month}', en: 'Month {month}: your move' },
  unitMonthsShort: { ru: 'мес', en: 'mo' },

  // --- Слейт ---
  slateSlots: { ru: 'Слотов занято {used} из {total} · содержание {cost}/мес', en: '{used} of {total} slots busy · upkeep {cost}/mo' },
  slateReadyTitle: { ru: 'Готово к выпуску: {count}', en: 'Ready to release: {count}' },
  slateReadyHint: { ru: 'Готовый проект можно придержать: выпустить в тихий месяц, ответить им на чужую премьеру или дождаться зимы. Но лежать не бесплатно — актуальность выветривается.', en: 'A finished project can be held back: released into a quiet month, used to answer a rival premiere, or saved for winter. But sitting on the shelf is not free — it goes stale.' },
  slateProductionTitle: { ru: 'В производстве: {count}', en: 'In production: {count}' },
  slateEmpty: { ru: 'В производстве пусто. Даже самый быстрый проект выйдет только через {months} месяца — премьер не будет всё это время.', en: 'Nothing in production. Even the fastest project lands only in {months} months — there will be no premieres until then.' },
  slateCommission: { ru: 'Запустить проект', en: 'Commission a project' },
  slateStart: { ru: 'Запустить', en: 'Commission' },
  slateNoSlots: { ru: 'Нет свободных слотов', en: 'No free slots' },
  slateNoCash: { ru: 'Не хватает кассы', en: 'Not enough cash' },
  slatePrice: { ru: 'Стоимость {price}, платится равными долями {months} месяцев', en: 'Costs {price}, paid in equal instalments over {months} months' },
  slateFocusHint: { ru: 'Проект под конкретный сегмент попадает в него точнее, но остальным интересен меньше: фокус — это всегда и отказ. «Для всех» — компромисс без перекоса.', en: 'A project aimed at one segment lands harder there and interests everyone else less: focus is always also a refusal. "Broad" is a compromise with no bias.' },
  slateBroad: { ru: 'Для всех', en: 'Broad' },
  slateFor: { ru: 'под {segment}', en: 'for {segment}' },
  slateHours: { ru: '{hours} ч контента', en: '{hours} h of content' },
  slateMonthsLeft: { ru: 'через {months} мес.', en: '{months} mo. out' },
  slateEstimate: { ru: 'Оценка качества: {low}–{high}. Точное значение будет известно на премьере.', en: 'Quality estimate: {low}–{high}. The exact figure is known only at release.' },
  slateQuality: { ru: 'качество {value}', en: 'quality {value}' },
  slateBuzz: { ru: 'шум {value}', en: 'buzz {value}' },
  slateFresh: { ru: 'свежий', en: 'fresh' },
  slateHeld: { ru: 'лежит {months} мес.', en: 'held {months} mo.' },
  slateStale: { ru: 'Пока лежит, потеряно {pct} шума премьеры.', en: 'While on the shelf it has lost {pct} of its premiere buzz.' },
  slateRelease: { ru: 'Выпустить в этом месяце', en: 'Release this month' },
  slateCancel: { ru: 'Отменить', en: 'Cancel' },
  slateCampaign: { ru: 'Кампания под релиз', en: 'Release campaign' },
  slateStartsNow: { ru: 'запустится в этом ходу, {months} мес. производства', en: 'starts this turn, {months} months of production' },

  // --- Ход месяца ---
  planNothing: { ru: 'На этот месяц ничего не запланировано', en: 'Nothing planned for this month' },
  planReleases: { ru: 'релизов: {count} на {budget}', en: 'releases: {count} for {budget}' },
  planCommission: { ru: 'запусков: {count} по {monthly}/мес', en: 'commissions: {count} at {monthly}/mo' },
  planRaise: { ru: 'повышение цены действующим', en: 'price rise for the existing base' },
  todoReleaseTitle: { ru: 'Готово к выпуску: {count}. Выпускать сейчас?', en: '{count} ready to release. Release now?' },
  todoReleaseVsRival: { ru: 'В следующем месяце у конкурента громкая премьера. Своя гасит чужую максимум на 65% — иногда выгоднее переждать и выйти в тихий месяц целиком.', en: 'The rival has a loud premiere next month. Yours cancels at most 65% of it — sometimes it pays more to wait and take a quiet month whole.' },
  todoReleaseGoodSeason: { ru: 'Сейчас {season} — смотрят больше обычного. Хороший месяц для премьеры.', en: 'It is {season} — people watch more than usual. A good month for a premiere.' },
  todoReleaseQuiet: { ru: 'Месяц спокойный: чужих премьер нет. Ваш шум никто не перебьёт.', en: 'A quiet month with no rival premieres. Nothing will drown out your noise.' },
  todoStudioTitle: { ru: 'В производстве пусто', en: 'Nothing in production' },
  todoStudioText: { ru: 'Запустите проект сейчас, иначе следующие месяцы пройдут без единой премьеры — а отток идёт всё это время.', en: 'Commission something now, or the coming months will pass without a single premiere — while churn runs the whole time.' },
  todoPriceGapTitle: { ru: 'База платит на {gap} меньше прайса', en: 'The base pays {gap} below list price' },
  todoPriceGapText: { ru: 'Новые подписываются по {list} ₽, действующие платят {paid} ₽. Перевести базу на прайс можно одним решением — но часть людей уйдёт именно из-за него.', en: 'New sign-ups pay ₽{list}, the existing base pays ₽{paid}. One decision moves them all onto list price — and some will leave precisely because of it.' },
  todoPriceGapCooldown: { ru: 'Повышать снова нельзя ещё {months} мес.: у людей есть память, и второе повышение подряд стоит гораздо дороже.', en: 'You cannot raise again for {months} months: people remember, and a second rise in a row costs far more.' },
  todoPriceGapDo: { ru: 'Перевести базу на прайс', en: 'Move the base to list price' },
  todoPriceGapOn: { ru: '✓ Переведём в этом месяце', en: '✓ Will move them this month' },
  todoMarketingTitle: { ru: 'Маркетинг при пустом каталоге', en: 'Marketing against an empty catalogue' },
  todoMarketingText: { ru: 'Приводить зрителя некуда: глубина каталога мала, и деньги сгорают. Сначала каталог, потом реклама.', en: 'There is nowhere to bring the viewer: catalogue depth is low and the money burns. Catalogue first, advertising after.' },
  todoCampaignTitle: { ru: 'Большой маркетинг без релиза', en: 'A big marketing budget with nothing to promote' },
  todoCampaignText: { ru: 'Бренд-маркетинг работает медленно. Кампания под конкретную премьеру даёт кратно больше — но премьеру для неё нужно иметь.', en: 'Brand marketing works slowly. A campaign behind a specific premiere does far more — but you need a premiere to put behind it.' },
  todoCalmTitle: { ru: 'Срочных решений нет', en: 'Nothing urgent' },
  todoCalmText: { ru: 'Можно двигать ползунки, запускать проекты или просто прожить месяц.', en: 'Adjust the sliders, commission something, or simply run the month.' },

  // --- Годовая подписка и цена ---
  kpiSubsFlat: { ru: 'без изменений', en: 'flat' },
  statPriceGap: { ru: 'Прайс / платят', en: 'List / paid' },
  statPriceGapSub: { ru: 'разрыв {gap} · годовых {annual}', en: 'gap {gap} · {annual} annual' },
  alertRaiseDone: { ru: 'Базу перевели на прайс. Из-за повышения ушло {lost} подписчиков — это и есть цена закрытия разрыва.', en: 'The base has been moved to list price. {lost} subscribers left over the rise — that is what closing the gap costs.' },
  alertAnnualCash: { ru: 'Годовые подписки принесли {cash} сразу. Это касса сегодня и зафиксированная цена на год вперёд.', en: 'Annual plans brought in {cash} at once. That is cash today and a locked price for a year.' },
  alertHeldTooLong: { ru: 'Готовые проекты лежат в запасе уже {months} мес. и теряют шум. Придерживать имеет смысл под конкретный месяц, а не «пока не понадобится».', en: 'Finished projects have been on the shelf for {months} months and are losing their buzz. Holding back works for a specific month, not for "until we need it".' },
  alertSlotsIdle: { ru: 'Свободных слотов: {count}. Слот стоит денег, даже когда пустует.', en: '{count} slots are idle. A slot costs money even when nothing is in it.' },

  // --- P&L ---
  pnlProduction: { ru: 'Производство (по проектам)', en: 'Production (by project)' },
  pnlSlots: { ru: 'Содержание студии', en: 'Studio upkeep' },
  pnlCampaigns: { ru: 'Кампании под релизы', en: 'Release campaigns' },



  // --- Живой конкурент ---
  stanceBuild: { ru: 'Ровный рост', en: 'Steady growth' },
  stanceBuildHint: { ru: 'Держит курс: умеренные бюджеты, цена чуть ниже вашей.', en: 'Holding course: moderate budgets, price a little under yours.' },
  stanceWar: { ru: 'Война цен', en: 'Price war' },
  stanceWarHint: { ru: 'Проигрывает и жжёт кассу: демпингует и заливает рынок маркетингом. Догонять его вниз по цене — проигрышная идея, он богаче.', en: 'Losing and burning cash: undercutting hard and flooding the market with marketing. Chasing him down on price is a losing idea — he has deeper pockets.' },
  stancePress: { ru: 'Давит', en: 'Pressing' },
  stancePressHint: { ru: 'Выигрывает и знает это: поднимает цену и наращивает бюджеты. Самое время отбирать у него зрителя, пока он дорожает.', en: 'Winning and knows it: raising price and increasing budgets. This is the moment to take viewers from him while he gets expensive.' },
  stanceHarvest: { ru: 'Снимает сливки', en: 'Harvesting' },
  stanceHarvestHint: { ru: 'Экономит: режет контент и маркетинг, поднимает цену и рекламу. Его каталог начнёт выдыхаться — ваш шанс.', en: 'Economising: cutting content and marketing, raising price and ad load. His catalogue will start going stale — that is your opening.' },
  stanceRetreat: { ru: 'Отступает', en: 'Retreating' },
  stanceRetreatHint: { ru: 'Деньги кончаются, раунды исчерпаны. Если додавить — рынок останется вам одному.', en: 'The money is running out and the rounds are used up. Push now and the market is yours alone.' },
  stanceGone: { ru: 'Ушёл с рынка', en: 'Out of the market' },
  stanceGoneHint: { ru: 'Конкурент обанкротился. Его подписчики расходятся по рынку несколько месяцев — успейте их забрать.', en: 'The rival has gone bust. His subscribers disperse over a few months — get to them first.' },

  rivalTheirPrice: { ru: 'Его цена:', en: 'His price:' },
  rivalPriceAbove: { ru: '(на {gap} ₽ дороже вас)', en: '({gap} ₽ above you)' },
  rivalPriceBelow: { ru: '(на {gap} ₽ дешевле вас)', en: '({gap} ₽ below you)' },
  rivalPriceSame: { ru: '(как у вас)', en: '(same as yours)' },
  rivalTheirCatalog: { ru: 'Его каталог:', en: 'His catalogue:' },
  rivalTheirOriginals: { ru: 'своего {hours}', en: '{hours} original' },
  rivalTheirFocus: { ru: 'Снимает:', en: 'Producing:' },
  shareYou: { ru: 'вы', en: 'you' },
  shareThem: { ru: 'он', en: 'rival' },
  shareBarHint: { ru: 'Доля рынка подписок: вы против конкурента', en: 'Share of the subscription market: you versus the rival' },
  shareCaption: { ru: 'У вас {you} подписчиков, у него {them}. Переток за месяц: {flow}.', en: 'You have {you} subscribers, he has {them}. Net switching this month: {flow}.' },

  // --- Совет директоров ---
  goalYear: { ru: 'Цель года {year}', en: 'Year {year} goal' },
  goalMonthsLeft: { ru: 'осталось {months} мес.', en: '{months} mo. left' },
  goalSubs: { ru: 'Набрать базу подписчиков: {have} из {need}', en: 'Build the subscriber base: {have} of {need}' },
  goalProfit: { ru: 'Доказать, что бизнес умеет быть прибыльным: {have} прибыльных месяцев из {need}, и база {subs} из {floor}', en: 'Prove the business can be profitable: {have} profitable months of {need}, and a base of {subs} of {floor}' },
  goalShare: { ru: 'Обойти конкурента: доля {have} из {need}, и база {subs} из {floor}', en: 'Overtake the rival: share {have} of {need}, and a base of {subs} of {floor}' },
  goalOnTrack: { ru: 'Цель выполнена — совет доволен, оценка компании выше.', en: 'Goal met — the board is happy and the valuation is higher.' },
  goalStake_dilution: { ru: 'Если провалить: совет введёт деньги сам и заберёт часть вашей доли.', en: 'If you miss: the board injects money itself and takes part of your stake.' },
  goalStake_contentCap: { ru: 'Если провалить: контентный бюджет режут на полгода.', en: 'If you miss: the content budget is capped for six months.' },
  goalStake_valuation: { ru: 'Если провалить: оценка компании на финише будет ниже.', en: 'If you miss: the final valuation takes a hit.' },
  goalPassed: { ru: 'выполнена', en: 'met' },
  goalFailed_dilution: { ru: 'провалена — размытие доли', en: 'missed — stake diluted' },
  goalFailed_contentCap: { ru: 'провалена — бюджет порезан', en: 'missed — budget capped' },
  goalFailed_valuation: { ru: 'провалена — оценка ниже', en: 'missed — valuation cut' },
  boardCapActive: { ru: 'Совет режет контентный бюджет до {cap} в месяц. Осталось {months} мес.', en: 'The board caps the content budget at {cap} a month. {months} mo. left.' },
  boardDone: { ru: 'Целей больше нет — идёт последний отрезок партии.', en: 'No goals left — this is the final stretch.' },

  // --- Кризисы ---
  crisisMonths: { ru: '{months}-й месяц', en: 'month {months}' },
  crisisWorsening: { ru: 'Пока решения нет, каждый месяц дороже предыдущего — и само решение тоже дорожает.', en: 'Until you decide, every month costs more than the last — and the fix gets more expensive too.' },

  // --- Новые показатели месяца ---
  statSwitch: { ru: 'Переток', en: 'Switching' },
  statSwitchSub: { ru: 'пришло {inn} · ушло {out}', en: '{inn} in · {out} out' },
  statPrices: { ru: 'Права / талант', en: 'Rights / talent' },
  statPricesSub: { ru: 'проект стоит {project}', en: 'a project costs {project}' },
  kpiShare: { ru: 'Доля рынка', en: 'Market share' },
  kpiShareSub: { ru: 'у конкурента {them}', en: 'rival has {them}' },

  // --- Новые предупреждения ---
  alertGoalPassed: { ru: 'Цель года {year} выполнена. Совет повышает оценку компании.', en: 'The year {year} goal is met. The board marks the company up.' },
  alertGoalFailed_dilution: { ru: 'Цель года {year} провалена. Совет ввёл деньги сам — и забрал часть вашей доли.', en: 'The year {year} goal was missed. The board injected money itself — and took part of your stake.' },
  alertGoalFailed_contentCap: { ru: 'Цель года {year} провалена. Контентный бюджет порезан на полгода: стратегия «вложим всё в рост» больше недоступна.', en: 'The year {year} goal was missed. The content budget is capped for six months: "pour everything into growth" is no longer available.' },
  alertGoalFailed_valuation: { ru: 'Цель года {year} провалена. Оценка компании на финише будет ниже.', en: 'The year {year} goal was missed. The final valuation takes a hit.' },
  alertCapped: { ru: 'Контентный бюджет урезан советом до {cap}. Лишние деньги просто не потрачены.', en: 'The board has capped the content budget at {cap}. The extra money simply was not spent.' },
  alertCrisisResolved: { ru: '«{name}» — решено за {cost}.', en: '"{name}" resolved for {cost}.' },
  alertLosingSubs: { ru: 'К конкуренту ушло {count} подписчиков. Люди не отказались от подписки — они выбрали другую.', en: '{count} subscribers went to the rival. They did not give up on streaming — they chose someone else.' },
  alertWinningSubs: { ru: 'От конкурента пришло {count} подписчиков: ваш сервис сейчас выглядит лучше.', en: '{count} subscribers came over from the rival: your service looks better right now.' },
  alertLicenseWar: { ru: 'Права подорожали в {index} раза: вы с конкурентом торгуетесь за один и тот же контент. Тот же бюджет покупает меньше часов.', en: 'Rights are {index}× more expensive: you and the rival are bidding for the same content. The same budget buys fewer hours.' },
  alertTalentCost: { ru: 'Талант подорожал в {index} раза. Успешному сервису звёзды выставляют другой счёт — себестоимость хита растёт быстрее его аудитории.', en: 'Talent is {index}× more expensive. Stars charge a successful service differently — a hit\u2019s cost grows faster than its audience.' },
  alertRivalRaised: { ru: 'Конкурент привлёк раунд. Ждите роста его бюджетов.', en: 'The rival has raised a round. Expect his budgets to grow.' },
  alertRivalDead: { ru: 'Конкурент обанкротился. Его база расходится по рынку — это ваш шанс забрать её.', en: 'The rival has gone bust. His base is dispersing — this is your chance to take it.' },

  // --- График войны ---
  chartWar: { ru: 'Вы и конкурент', en: 'You and the rival' },
  chartWarCaption: { ru: 'Рынок один на двоих. Расти можно, приводя новых или переманивая чужих, — и второй способ работает быстрее.', en: 'One market for the two of you. You can grow by bringing in new viewers or by taking his — and the second is faster.' },
  seriesYou: { ru: 'Вы', en: 'You' },
  seriesThem: { ru: 'Конкурент', en: 'Rival' },


  panelDynamics: { ru: 'Динамика', en: 'Trends' },
  leverWhy: { ru: 'зачем это?', en: 'why does this matter?' },

  // --- сводка под ползунками ---
  opsCatalog: { ru: 'Каталог: <a class="jump" data-jump="panel:slate">{hours}</a> часов ({licensed} лицензий + {original} своих). Глубина <b>{depth}</b>, свежесть <b>{fresh}</b>.', en: 'Catalogue: <a class="jump" data-jump="panel:slate">{hours}</a> hours ({licensed} licensed + {original} original). Depth <b>{depth}</b>, freshness <b>{fresh}</b>.' },
  opsLicensing: { ru: 'Бюджет лицензий купит <a class="jump" data-jump="lever:licensing">{hours}</a> часов в месяц, из них истечёт {decay} за месяц.', en: 'The licensing budget buys <a class="jump" data-jump="lever:licensing">{hours}</a> hours a month; {decay} of the library expires each month.' },
  opsUnitCheck: { ru: 'Подписчик приносит <a class="jump" data-jump="tab:unit">{arpu}</a> и стоит <b>{cost}</b> трафика и поддержки → вклад <b class="{cls}">{cm}</b>.', en: 'A subscriber brings <a class="jump" data-jump="tab:unit">{arpu}</a> and costs <b>{cost}</b> in bandwidth and support → contribution <b class="{cls}">{cm}</b>.' },
  opsAdShare: { ru: 'На дешёвый тариф уходит примерно <a class="jump" data-jump="lever:priceAds">{share}</a> подписчиков — они платят меньше, но приносят рекламу.', en: 'Roughly <a class="jump" data-jump="lever:priceAds">{share}</a> of subscribers pick the cheap tier — they pay less but bring advertising.' },

  // --- студия ---
  studioGenre: { ru: 'Во что вкладывается студия', en: 'What the studio is making' },
  studioProject: { ru: 'Проект стоит {cost} и выйдет через {months} мес.', en: 'A project costs {cost} and premieres in {months} months.' },
  studioFund: { ru: 'Накоплено на текущий проект: <b>{fund}</b> из {cost}.', en: 'Saved towards the current project: <b>{fund}</b> of {cost}.' },
  studioPipelineEmpty: { ru: 'В производстве ничего нет. Премьеры не будет — а значит, не будет и причины подписаться.', en: 'Nothing is in production. There will be no premiere — and therefore no reason to subscribe.' },
  studioPipeline: { ru: 'В производстве: {list}.', en: 'In production: {list}.' },
  studioPipelineItem: { ru: '{genre} через {months} мес.', en: '{genre} in {months} mo.' },
  studioLag: { ru: 'Деньги уходят сегодня, зритель увидит результат через полгода. Решение о премьере вы принимаете сейчас — вслепую.', en: 'The money goes out today and viewers see the result in six months. You are deciding about that premiere now, blind.' },

  // --- афиша конкурента ---
  rivalPanel: { ru: 'Афиша конкурента · {season}, месяц {month}', en: 'Rival line-up · {season}, month {month}' },
  rivalNow: { ru: 'этот месяц', en: 'this month' },
  rivalNext: { ru: 'анонсировано на следующий', en: 'announced for next month' },
  rivalNone: { ru: 'Тихо', en: 'Quiet' },
  rivalSmall: { ru: 'Проходной релиз', en: 'Minor release' },
  rivalNotable: { ru: 'Заметная премьера', en: 'Notable premiere' },
  rivalMajor: { ru: 'Крупная премьера', en: 'Major premiere' },
  rivalMega: { ru: 'Событие года', en: 'Event of the year' },
  rivalNoEffect: { ru: 'ничего не отвлекает зрителя', en: 'nothing is competing for attention' },
  rivalEffects: { ru: 'приток новых <b class="down">{acq}</b>, отток <b class="down">+{churn} п.п.</b>, часы <b class="down">{hours}</b>', en: 'new sign-ups <b class="down">{acq}</b>, churn <b class="down">+{churn} pp</b>, hours <b class="down">{hours}</b>' },
  rivalAdvice: { ru: 'В следующем месяце зрителя будут звать в другое место. Своя громкая премьера гасит чужую — но её нужно было запустить в производство полгода назад. Что можно сейчас: усилить маркетинг или переждать и не жечь бюджет впустую.', en: 'Next month someone else will be calling your viewers away. Your own loud premiere blunts theirs — but it had to enter production six months ago. What you can still do: push marketing, or sit it out and not burn the budget for nothing.' },

  seasonWinter: { ru: 'зима', en: 'winter' },
  seasonSpring: { ru: 'весна', en: 'spring' },
  seasonSummer: { ru: 'лето', en: 'summer' },
  seasonAutumn: { ru: 'осень', en: 'autumn' },

  // --- что в индустрии ---
  newsPanel: { ru: 'Что в индустрии', en: 'What is going on in the industry' },
  newsEmpty: { ru: 'Месяц без событий: ни премьер, ни новостей от соседа. Такие месяцы и показывают настоящую экономику подписки — без всплесков от премьер.', en: 'A month with nothing in it: no premieres, no news from next door. These are the months that show the real economics of a subscription — without the premiere spikes.' },
  newsPremiere: { ru: '<b>Премьера: {genre}, {scale}.</b> Качество {quality}.{held} Всплеск смотрения держится месяц, а платить за него будут те, кто останется после.', en: '<b>Premiere: {genre}, {scale}.</b> Quality {quality}.{held} The viewing spike lasts a month; the ones who pay for it are the ones who stay after.' },
  newsPremiereHeld: { ru: ' Проект пролежал в запасе {months} мес. и за это время подвыветрился.', en: ' The project sat in the vault for {months} months and went a little stale.' },
  newsNoPremiere: { ru: 'В этом месяце вы ничего не выпустили. В запасе готовых проектов: {vault}. Пустой месяц не бесплатен: без новинок база вспоминает, что подписку можно отменить.', en: 'You released nothing this month. Finished projects in the vault: {vault}. An empty month is not free: with nothing new, the base remembers that a subscription can be cancelled.' },
  newsRivalLoud: { ru: '<b>У конкурента на следующий месяц заявлено: {release}.</b> Внимание зрителя в этот месяц будет делиться, а не складываться: выпускать своё крупное рядом — значит платить за кампанию дважды.', en: '<b>Announced next door for next month: {release}.</b> Attention that month gets divided, not added: putting your own big release beside it means paying for the campaign twice.' },
  newsRivalQuiet: { ru: 'У конкурента на следующий месяц заявлено: {release}. Тихий месяц у соседа — лучшее окно для вашей премьеры.', en: 'Announced next door for next month: {release}. A quiet month next door is the best window for your own premiere.' },
  newsRivalStance: { ru: '<b>Конкурент меняет тактику: {stance}.</b> {note}', en: '<b>The rival changes tack: {stance}.</b> {note}' },
  newsRivalRaised: { ru: '<b>Конкурент поднял раунд.</b> Теперь ему есть на что демпинговать и перекупать права — и то и другое вы почувствуете не сразу.', en: '<b>The rival has raised a round.</b> Now they have money to undercut you and to outbid you for rights — and you will feel both with a delay.' },
  newsRights: { ru: '<b>Истекли права на {gone} ч каталога,</b> куплено за месяц {bought} ч. {verdict}', en: '<b>Rights expired on {gone} h of the catalogue,</b> {bought} h bought this month. {verdict}' },
  newsRightsShrink: { ru: 'Каталог тает: лицензии — это аренда, и платить надо каждый месяц просто чтобы остаться на месте. Своё этого не требует.', en: 'The catalogue is shrinking: licences are rent, and you pay every month just to stand still. Your own titles do not ask for that.' },
  newsRightsHold: { ru: 'Закупка покрывает истечение — каталог держится. Ровно поэтому лицензионные часы дешевле собственных только на первый взгляд.', en: 'Buying covers the expiry — the catalogue holds. This is exactly why licensed hours only look cheaper than your own.' },
  newsCliffSoon: { ru: '<b>Студии готовят собственные витрины: через {months} мес. с рынка отзовут около {share} лицензионных каталогов.</b> Удар придётся по всем — устоит тот, у кого к тому времени будет своё.', en: '<b>The studios are building their own storefronts: in {months} months about {share} of licensed catalogues will be pulled from the market.</b> Everyone takes the hit — whoever owns their own content by then stays standing.' },
  newsCliffHit: { ru: '<b>Обвал прав: студии отозвали {lost} ч вашего лицензионного каталога.</b> У конкурента полка похудела так же. Дальше решает собственный контент.', en: '<b>The rights cliff: the studios pulled {lost} h of your licensed catalogue.</b> The rival’s shelf just got thinner too. From here on, original content decides.' },
  newsRivalSurge: { ru: '<b>Конкурент закрыл внеплановый раунд и объявляет ценовую войну до конца года.</b> Досидеть финал на автопилоте не получится.', en: '<b>The rival has closed an unscheduled round and is declaring a price war until the end of the year.</b> You will not coast through the finale on autopilot.' },
  newsLicensePrice: { ru: '<b>Права подорожали: ×{index} к базовой цене часа.</b> Когда за одни и те же сериалы торгуетесь вы оба, дороже становится обоим.', en: '<b>Rights have gone up: ×{index} on the base price per hour.</b> When you both bid for the same shows, both of you pay more.' },
  newsTalentPrice: { ru: '<b>Талант подорожал: ×{index} к базовой смете.</b> Режиссёров и актёров на рынке столько же, сколько было, а денег у индустрии стало больше.', en: '<b>Talent has gone up: ×{index} on the base budget.</b> There are as many directors and actors as before; there is just more money chasing them.' },
  newsFinished: { ru: '<b>Проект доснят: {genre}, {scale}.</b> Его можно выпускать сейчас, а можно придержать до нужного месяца — но в запасе он выветривается.', en: '<b>A project is finished: {genre}, {scale}.</b> You can release it now or hold it for the right month — but it goes stale in the vault.' },
  newsPartnerExpired: { ru: '<b>Договор с партнёром закончился: {name}.</b> Подписчиков ушло {lost}, осталось {kept}. Оптовая база уходит вместе с договором — она была не ваша.', en: '<b>A partner deal has ended: {name}.</b> {lost} subscribers left, {kept} stayed. A wholesale base leaves with the contract — it was never yours.' },
  newsSeasonWinter: { ru: '<b>Начинается зима — высокий сезон.</b> Смотрят почти на пятую часть больше обычного, и премьеры соседа тоже придутся на эти месяцы.', en: '<b>Winter is starting — the high season.</b> People watch almost a fifth more than usual, and the rival premieres will land in these months too.' },
  newsSeasonSpring: { ru: '<b>Начинается весна.</b> Смотрение возвращается к обычному: всплеск зимних премьер закончился, платить продолжают уже по привычке.', en: '<b>Spring is starting.</b> Viewing returns to normal: the winter premiere spike is over, and people keep paying out of habit.' },
  newsSeasonSummer: { ru: '<b>Начинается лето — низкий сезон.</b> Смотрят меньше всего в году. Крупную премьеру летом видит меньше людей за те же деньги на кампанию.', en: '<b>Summer is starting — the low season.</b> This is the least-watched part of the year. A big premiere in summer reaches fewer people for the same campaign money.' },
  newsSeasonAutumn: { ru: '<b>Начинается осень.</b> Зрители возвращаются к экрану — это разгон перед зимой и хорошее время выпускать то, что лежит в запасе.', en: '<b>Autumn is starting.</b> Viewers come back to the screen — this is the run-up to winter and a good time to release what is sitting in the vault.' },

  // --- алгоритмы ---
  algoData: { ru: 'Данные', en: 'Data' },
  algoTeam: { ru: 'Команда', en: 'Team' },
  algoQuality: { ru: 'Качество', en: 'Quality' },
  algoDataHint: { ru: 'Накопленные часы просмотра — обучающая выборка', en: 'Accumulated watch hours — your training set' },
  algoTeamHint: { ru: 'Накопленные вложения в data science', en: 'Cumulative investment in data science' },
  algoQualityHint: { ru: 'Среднее геометрическое: нужно и то и другое', en: 'Geometric mean: you need both halves' },
  algoIntro: { ru: 'Качество алгоритмов = √(данные × команда). Часы просмотра приходят только от подписчиков, поэтому рекомендации нельзя построить раньше, чем появится кому рекомендовать.', en: 'Algorithm quality = √(data × team). Watch hours only come from subscribers, so you cannot build recommendations before there is somebody to recommend to.' },
  algoInstalled: { ru: 'внедрён', en: 'live' },
  algoInstallCost: { ru: 'внедрение {cost}', en: 'rollout {cost}' },
  algoNeedQuality: { ru: 'нужно качество {value}', en: 'needs quality {value}' },
  algoPending: { ru: 'Будет внедрён при переходе к следующему месяцу: разовые {cost}.', en: 'Will be rolled out when you run the next month: a one-off {cost}.' },

  // --- финансирование ---
  fundingTake: { ru: 'Взять', en: 'Take it' },
  fundingDilution: { ru: 'размытие {dilution} → ваша доля {equity}', en: 'dilution {dilution} → your stake {equity}' },
  fundingHead: { ru: 'Оценка компании: <b>{valuation}</b> (pre-money). Ваша доля: <b>{equity}</b>, привлечено: {raised}.', en: 'Company valuation: <b>{valuation}</b> (pre-money). Your stake: <b>{equity}</b>, raised so far: {raised}.' },
  fundingNote: { ru: 'В оценку входит и собственная библиотека: оригиналы — актив, лицензии — аренда. Поэтому два сервиса с одинаковой выручкой стоят по-разному.', en: 'The valuation includes your own library: originals are an asset, licences are rent. That is why two services with identical revenue are worth different amounts.' },
  fundingLocked: { ru: '<br><b>Раунд доступен с {month}-го месяца.</b>', en: '<br><b>Rounds open from month {month}.</b>' },
  fundingDone: { ru: 'Раунд закрыт: {amount} за {dilution} компании.', en: 'Round closed: {amount} for {dilution} of the company.' },

  // --- события ---
  eventAuto: { ru: 'Событие сработает автоматически при переходе к следующему месяцу.', en: 'This event resolves automatically when you run the next month.' },
  eventLesson: { ru: 'Экономический смысл:', en: 'What this teaches:' },
  eventChoiceNeeded: { ru: 'Сначала выберите решение по событию месяца.', en: 'Choose how to handle this month’s event first.' },

  // --- отчёт ---
  reportMonth0: { ru: 'Месяц 0. Сервис ещё не запущен.', en: 'Month 0. The service has not launched yet.' },
  reportStartTitle: { ru: 'С чего начать.', en: 'Where to start.' },
  reportStartIntro: { ru: 'У вас {cash} и библиотека из нескольких сотен часов старого кино. Порядок почти всегда такой:', en: 'You have {cash} and a library of a few hundred hours of old films. The sequence is almost always this:' },
  reportStart1: { ru: 'Включите <a class="jump" data-jump="lever:licensing">закупку лицензий</a>: каталог нужен прямо сейчас, а собственный проект выйдет только через полгода.', en: 'Turn on <a class="jump" data-jump="lever:licensing">licensing</a>: you need a catalogue right now, and your own project will not premiere for six months.' },
  reportStart2: { ru: 'Одновременно запустите <a class="jump" data-jump="panel:slate">производство</a>. Оригинал — единственное, чего нет у конкурента, и он остаётся вашим навсегда.', en: 'At the same time start <a class="jump" data-jump="panel:slate">production</a>. An original is the only thing your rival does not have, and it stays yours forever.' },
  reportStart3: { ru: 'Проверьте вклад с подписчика: трафик растёт вместе с просмотром, и слишком щедрый битрейт съедает подписку целиком.', en: 'Check contribution per subscriber: bandwidth grows with viewing, and an over-generous bitrate can swallow the whole subscription fee.' },
  reportStart4: { ru: 'Только потом включайте <a class="jump" data-jump="lever:brandMarketing">маркетинг</a>. Приводить зрителя в пустой каталог — самый дорогой способ купить отток.', en: 'Only then turn on <a class="jump" data-jump="lever:brandMarketing">marketing</a>. Bringing viewers into an empty catalogue is the most expensive way to buy churn.' },
  reportStartAlgos: { ru: '<a class="jump" data-jump="panel:algos">Алгоритмы</a> откроются позже: им нужны часы просмотра, а часы приходят только от подписчиков.', en: '<a class="jump" data-jump="panel:algos">Algorithms</a> unlock later: they need watch hours, and hours only come from subscribers.' },
  reportTitle: { ru: 'Итоги месяца {month}', en: 'Month {month} results' },
  reportHeadStats: { ru: 'выручка {revenue} · подписка {subscription} · реклама {ads}', en: 'revenue {revenue} · subscriptions {subscription} · advertising {ads}' },

  statSubs: { ru: 'Подписчики', en: 'Subscribers' },
  statSubsSub: { ru: '+{gained} / −{lost}', en: '+{gained} / −{lost}' },
  statHours: { ru: 'Часы просмотра', en: 'Watch hours' },
  statHoursSub: { ru: '{perSub} ч на подписчика', en: '{perSub} h per subscriber' },
  unitHours: { ru: 'ч', en: 'h' },
  genreHours: { ru: '{hours} ч контента', en: '{hours} h of content' },
  statCatalog: { ru: 'Каталог', en: 'Catalogue' },
  statCatalogSub: { ru: 'своих {original} ч ({share})', en: '{original} h original ({share})' },
  statFresh: { ru: 'Свежесть', en: 'Freshness' },
  statFreshSub: { ru: 'глубина ×{depth}', en: 'depth ×{depth}' },
  statChurn: { ru: 'Отток', en: 'Churn' },
  statChurnSub: { ru: 'после премьеры +{hangover}', en: 'post-premiere +{hangover}' },
  statArpu: { ru: 'ARPU', en: 'ARPU' },
  statArpuSub: { ru: 'вклад {value}', en: 'contribution {value}' },
  statTraffic: { ru: 'Трафик', en: 'Bandwidth' },
  statTrafficSub: { ru: '{perHour} ₽ за час', en: '₽{perHour} per hour' },
  statProfit: { ru: 'Прибыль', en: 'Profit' },
  statProfitSub: { ru: 'постоянные {value}', en: 'fixed costs {value}' },
  statCacLtv: { ru: 'CAC / LTV', en: 'CAC / LTV' },
  statCacOff: { ru: 'маркетинг выключен', en: 'marketing is off' },

  premiereNote: { ru: 'Премьера: {list}. Шум привёл подписчиков — но через месяц те, кто пришёл только ради неё, начнут уходить.', en: 'Premiere: {list}. The buzz brought subscribers in — but a month from now the ones who came only for it will start leaving.' },
  premiereItem: { ru: '{genre} (качество {quality})', en: '{genre} (quality {quality})' },
  startedNote: { ru: 'Запущено в производство: {list}. Премьера через {months} мес.', en: 'Entered production: {list}. Premiere in {months} months.' },
  installNote: { ru: 'Внедрено: {names} — разовые {cost}.', en: 'Rolled out: {names} — a one-off {cost}.' },

  driversTitle: { ru: 'Из чего сложилось изменение базы ({delta})', en: 'What the change in the base is made of ({delta})' },
  driversNet: { ru: 'Итого', en: 'Net' },
  flowNew: { ru: 'Новые подписки', en: 'New subscriptions' },
  flowChurn: { ru: 'Отток', en: 'Churn' },
  flowSwitch: { ru: 'Переток с конкурентом', en: 'Switching with the rival' },
  flowPartners: { ru: 'Партнёрства', en: 'Partnerships' },
  flowRaise: { ru: 'Ушли после повышения цены', en: 'Left after the price rise' },
  factorsIntro: { ru: 'Условия месяца изменились так:', en: 'Conditions changed like this:' },
  factorPrice: { ru: 'доступность цены', en: 'price affordability' },
  factorCatalog: { ru: 'каталог и новинки', en: 'catalogue and new releases' },
  factorAds: { ru: 'терпимость к рекламе', en: 'ad tolerance' },
  factorStanding: { ru: 'позиция против конкурента', en: 'standing against the rival' },
  factorAwareness: { ru: 'узнаваемость', en: 'awareness' },
  factorRetention: { ru: 'удержание', en: 'retention' },

  // --- предупреждения ---
  alertNoCatalog: { ru: 'Каталог почти пуст: глубина ×{depth}. Приводить зрителя некуда — маркетинг сейчас сгорает впустую.', en: 'The catalogue is nearly empty: depth ×{depth}. There is nowhere to bring viewers — marketing simply burns right now.' },
  alertStale: { ru: 'Новинок нет: свежесть ×{fresh}. Каталог не стал меньше, но зритель видит одно и то же и уходит — за месяц {lost}.', en: 'No new releases: freshness ×{fresh}. The catalogue has not shrunk, but viewers see the same shelf and leave — {lost} this month.' },
  alertNoPipeline: { ru: 'В производстве пусто. Через полгода у вас не будет ни одной премьеры, и остановить отток будет нечем.', en: 'Production is empty. In six months you will have no premiere at all and nothing to stop the churn with.' },
  alertNegativeCm: { ru: 'Вклад с подписчика отрицательный ({value}). Каждый новый зритель увеличивает убыток: трафик дороже подписки.', en: 'Contribution per subscriber is negative ({value}). Every new viewer deepens the loss: bandwidth costs more than the subscription.' },
  alertTrafficHeavy: { ru: 'Трафик съедает {share} выручки ({cost}). При {hours} ч на подписчика битрейт {bitrate} Мбит/с — дорогое удовольствие.', en: 'Bandwidth eats {share} of revenue ({cost}). At {hours} h per subscriber, {bitrate} Mbps is an expensive luxury.' },
  alertBreakEven: { ru: 'Вклад с подписчика {cm}, постоянных расходов на {fixed}. Точка безубыточности: {subs} подписчиков.', en: 'Contribution per subscriber is {cm} against {fixed} of fixed costs. Break-even sits at {subs} subscribers.' },
  alertRunway: { ru: 'Денег на {months} месяцев при текущем сжигании {burn}/мес. Контентные бюджеты — первое, что придётся резать.', en: '{months} months of cash left at the current burn of {burn}/mo. Content budgets are the first thing you will have to cut.' },
  alertHangover: { ru: 'Волна отписок после премьеры: отток вырос до {churn}. Те, кто пришёл ради одного сериала, уходят, досмотрев его.', en: 'A post-premiere wave: churn is up to {churn}. Everyone who came for one show leaves once they have finished it.' },
  alertRivalAhead: { ru: 'В следующем месяце у конкурента {release}. Приток новых упадёт примерно до {acq} — либо отвечайте премьерой, либо не тратьте маркетинг впустую.', en: 'Next month the rival has {release}. New sign-ups will fall to about {acq} — either answer with a premiere or do not waste marketing.' },
  alertAdHeavy: { ru: 'Реклама {load} мин/час приносит {revenue}, но поднимает отток. Киноманы уходят от неё втрое быстрее молодёжи.', en: 'An ad load of {load} min/hr brings {revenue} but lifts churn. Cinephiles leave over it three times faster than young viewers.' },
  alertLtvCacBad: { ru: 'LTV/CAC = {value}: подписчик не отобьёт стоимость своего привлечения.', en: 'LTV/CAC = {value}: a subscriber will not repay the cost of acquiring them.' },
  alertLtvCacGood: { ru: 'LTV/CAC = {value} — привлечение окупается с запасом, есть смысл давить на маркетинг.', en: 'LTV/CAC = {value} — acquisition pays back with room to spare, so it is worth pushing marketing.' },
  alertRndIdle: { ru: 'Data Science стоит {cost}/мес, но ни один алгоритм не включён. Команда копит качество ({quality}), а деньги делают только внедрённые правила.', en: 'Data science costs {cost}/mo but no algorithm is switched on. The team is building quality ({quality}); only deployed rules make money.' },
  alertAlgosReady: { ru: 'Доступно к внедрению: {names}. Качество алгоритмов {quality}.', en: 'Ready to roll out: {names}. Algorithm quality is {quality}.' },
  alertProfit: { ru: 'Месяц закрыт в плюс: {value}.', en: 'The month closed in the black: {value}.' },

  // --- графики ---
  chartSubs: { ru: 'Подписчики', en: 'Subscribers' },
  chartSubsCaption: { ru: 'Три нижние линии складываются в верхнюю. Оптовая база растёт по контракту, а не от вашей работы — и уходит разом, когда контракт кончается.', en: 'The three lower lines add up to the top one. The wholesale base grows by contract, not by your work — and leaves all at once when the contract ends.' },
  seriesSubs: { ru: 'Всего', en: 'Total' },
  seriesPremium: { ru: 'Без рекламы', en: 'Ad-free' },
  seriesAds: { ru: 'С рекламой', en: 'Ad tier' },
  seriesPartner: { ru: 'Оптовые (партнёрства)', en: 'Wholesale (partnerships)' },
  chartMoney: { ru: 'Деньги', en: 'Money' },
  chartMoneyCaption: { ru: 'Вклад = выручка − трафик и поддержка. Прибыль = вклад − контент, маркетинг и офис. Контент здесь постоянные расходы: они не зависят от числа зрителей.', en: 'Contribution = revenue − bandwidth and support. Profit = contribution − content, marketing and overheads. Content is a fixed cost here: it does not depend on how many people watch.' },
  seriesRevenue: { ru: 'Выручка', en: 'Revenue' },
  seriesContribution: { ru: 'Вклад', en: 'Contribution' },
  seriesProfit: { ru: 'Прибыль', en: 'Profit' },
  chartCash: { ru: 'Касса', en: 'Cash' },
  chartCashCaption: { ru: 'Контентные бюджеты уходят каждый месяц, а премьера окупается через полгода. Между этими двумя фактами и живёт касса.', en: 'Content budgets go out every month while a premiere pays back six months later. Your cash lives in the gap between those two facts.' },
  chartCatalog: { ru: 'Каталог', en: 'Catalogue' },
  chartCatalogCaption: { ru: 'Лицензии истекают каждый месяц: чтобы каталог просто не уменьшался, платить нужно постоянно. Оригиналы не истекают никогда.', en: 'Licences expire every month: keeping the catalogue merely level requires paying forever. Originals never expire.' },
  seriesLicensed: { ru: 'Лицензии, ч', en: 'Licensed, h' },
  seriesOriginal: { ru: 'Свои, ч', en: 'Original, h' },
  chartEngagement: { ru: 'Просмотр', en: 'Engagement' },
  chartEngagementCaption: { ru: 'Часы на подписчика — одновременно лучший индикатор лояльности и крупнейшая статья переменных расходов. Радоваться им нужно осторожно.', en: 'Hours per subscriber is at once your best loyalty indicator and your largest variable cost. Enjoy it carefully.' },
  seriesHoursPerSub: { ru: 'Часов на подписчика', en: 'Hours per subscriber' },
  seriesChurn: { ru: 'Отток, %', en: 'Churn, %' },
  chartUnit: { ru: 'Юнит', en: 'Unit' },
  chartUnitCaption: { ru: 'ARPU против вклада: разница между ними — трафик и поддержка. Чем больше смотрят, тем шире эта щель.', en: 'ARPU against contribution: the gap between them is bandwidth and support. The more people watch, the wider it gets.' },
  seriesArpu: { ru: 'ARPU, ₽', en: 'ARPU, ₽' },
  seriesCmPerSub: { ru: 'Вклад с подписчика, ₽', en: 'Contribution per subscriber, ₽' },
  chartAlgos: { ru: 'Алгоритмы', en: 'Algorithms' },
  chartAlgosCaption: { ru: 'Качество алгоритмов = √(данные × команда). Данные копятся только от часов просмотра, поэтому кривая всегда отстаёт от роста базы.', en: 'Algorithm quality = √(data × team). Data only accumulates from watch hours, so the curve always lags behind the base.' },
  seriesQuality: { ru: 'Качество, %', en: 'Quality, %' },
  seriesData: { ru: 'Данные, %', en: 'Data, %' },
  seriesTeam: { ru: 'Команда, %', en: 'Team, %' },

  // --- вкладки ---
  tabUnit: { ru: 'Юнит-экономика', en: 'Unit economics' },
  tabPnl: { ru: 'P&L', en: 'P&L' },
  tabAlgos: { ru: 'Алгоритмы', en: 'Algorithms' },
  tabSegments: { ru: 'Аудитория', en: 'Audience' },
  tabHelp: { ru: 'Справка', en: 'Guide' },

  // --- юнит-экономика ---
  unitIntro: { ru: 'Экономика одного подписчика в месяц при текущих настройках — пересчитывается мгновенно, до перехода к следующему месяцу.', en: 'The economics of one subscriber per month at your current settings — recalculated instantly, before you run the next month.' },
  unitColItem: { ru: 'Статья', en: 'Line' },
  unitColPerSub: { ru: '₽ / подписчик', en: '₽ / subscriber' },
  unitSubscription: { ru: 'Подписка', en: 'Subscription' },
  unitAdvertising: { ru: 'Реклама', en: 'Advertising' },
  unitRevenue: { ru: 'ARPU (выручка с подписчика)', en: 'ARPU (revenue per subscriber)' },
  unitCdn: { ru: 'Трафик ({hours} ч × {perHour} ₽)', en: 'Bandwidth ({hours} h × ₽{perHour})' },
  unitSupport: { ru: 'Поддержка и биллинг', en: 'Support and billing' },
  unitContribution: { ru: 'Вклад с подписчика', en: 'Contribution per subscriber' },
  unitNote: { ru: 'Обратите внимание: контента в этой таблице нет. Он не переменный расход — он постоянный, и потому определяет не выгодность подписчика, а необходимый масштаб.', en: 'Note what is missing: content. It is not a variable cost but a fixed one, so it does not decide whether a subscriber is worth having — it decides what scale you need.' },
  unitBreakEven: { ru: 'При постоянных расходах {fixed}/мес точка безубыточности — <b>{subs} подписчиков</b> (сейчас {current}).', en: 'At fixed costs of {fixed}/mo, break-even is <b>{subs} subscribers</b> (currently {current}).' },
  unitNoBreakEven: { ru: 'Вклад с подписчика ≤ 0: точки безубыточности не существует ни при каком масштабе. Сначала чините экономику, потом растите.', en: 'Contribution per subscriber is ≤ 0, so break-even does not exist at any scale. Fix the economics first, then grow.' },
  unitAcquisition: { ru: 'Привлечение подписчика', en: 'Subscriber acquisition' },
  unitCac: { ru: 'CAC (маркетинг / новые подписчики)', en: 'CAC (marketing / new subscribers)' },
  unitLifetime: { ru: 'Срок жизни подписки', en: 'Subscription lifetime' },
  unitLifetimeValue: { ru: '{value} мес.', en: '{value} mo.' },
  unitLtv: { ru: 'LTV (вклад за всё время жизни)', en: 'LTV (lifetime contribution)' },
  unitLtvCacNote: { ru: 'Ориентир индустрии: LTV/CAC ≥ 3. В стриминге эта величина обманчива: она не учитывает контент, без которого подписчик не остался бы ни на месяц.', en: 'The industry benchmark is LTV/CAC ≥ 3. In streaming the number is deceptive: it ignores the content without which the subscriber would not have stayed a single month.' },

  // --- P&L ---
  pnlEmpty: { ru: 'Отчёт появится после первого прожитого месяца.', en: 'The statement appears after your first completed month.' },
  pnlSubscription: { ru: 'Выручка от подписки', en: 'Subscription revenue' },
  pnlAds: { ru: 'Выручка от рекламы', en: 'Advertising revenue' },
  pnlRevenue: { ru: 'Выручка', en: 'Revenue' },
  pnlCdn: { ru: 'Трафик', en: 'Bandwidth' },
  pnlSupport: { ru: 'Поддержка и биллинг', en: 'Support and billing' },
  pnlWinback: { ru: 'Удерживающие скидки', en: 'Retention discounts' },
  pnlContribution: { ru: 'Вклад (contribution)', en: 'Contribution' },
  pnlLicensing: { ru: 'Закупка лицензий', en: 'Licensing' },
  pnlOriginals: { ru: 'Производство оригиналов', en: 'Originals production' },
  pnlMarketing: { ru: 'Маркетинг', en: 'Marketing' },
  pnlTech: { ru: 'Технологии', en: 'Technology' },
  pnlRnd: { ru: 'Data Science', en: 'Data science' },
  pnlUpkeep: { ru: 'Содержание технологий', en: 'Technology upkeep' },
  pnlUpkeepNote: { ru: 'Содержание растёт от всего, что уже построено, серверы — от нагрузки. Обе статьи дорожают ровно тогда, когда дела идут хорошо.', en: 'Upkeep grows with everything already built, servers with the load. Both get more expensive exactly when things go well.' },
  pnlHq: { ru: 'Студия, редакция, офис', en: 'Studio, editorial, overheads' },
  pnlStaff: { ru: 'Штат: продукт, биллинг, юристы', en: 'Staff: product, billing, legal' },
  pnlOperatingProfit: { ru: 'Операционная прибыль', en: 'Operating profit' },
  pnlOneOff: { ru: 'Разовые расходы (внедрения, события)', en: 'One-off costs (rollouts, events)' },
  pnlCashChange: { ru: 'Изменение кассы', en: 'Change in cash' },
  pnlNote: { ru: 'Контент стоит одинаково при десяти тысячах подписчиков и при десяти миллионах. Именно поэтому стриминг — бизнес масштаба, а не бизнес маржи.', en: 'Content costs the same with ten thousand subscribers as with ten million. That is exactly why streaming is a scale business rather than a margin business.' },

  // --- аудитория ---
  segmentsEmpty: { ru: 'Данные появятся после первого месяца.', en: 'Data appears after the first month.' },
  colSegment: { ru: 'Сегмент', en: 'Segment' },
  colSubs: { ru: 'Подписчики', en: 'Subscribers' },
  colAdShare: { ru: 'Тариф с рекламой', en: 'Ad tier' },
  colChurn: { ru: 'Отток', en: 'Churn' },
  colArpu: { ru: 'Платит / мес', en: 'Pays / mo' },
  colPenetration: { ru: 'Охват', en: 'Reach' },
  colPriceFactor: { ru: 'Цена', en: 'Price' },
  colAppeal: { ru: 'Каталог', en: 'Catalogue' },
  colAdPenalty: { ru: 'Реклама', en: 'Ads' },
  factorsNote: {
    ru: 'Три причины, по которым сегмент подписывается охотнее или неохотнее. <b>1.00 — норма.</b> Больше единицы — фактор работает на вас в этом сегменте, меньше — против. Охват — доля сегмента, которая о вас вообще слышала.',
    en: 'The three reasons a segment signs up more or less readily. <b>1.00 is normal.</b> Above one the factor works for you in that segment, below one against. Reach is the share of the segment that has heard of you at all.',
  },
  segmentsNote: { ru: 'Один и тот же рычаг работает в сегментах по-разному: рубль цены пугает молодёжь и не замечается киноманами, а минута рекламы прогоняет киноманов и не трогает молодёжь.', en: 'The same lever behaves differently by segment: a rouble of price scares young viewers and goes unnoticed by cinephiles, while a minute of advertising drives cinephiles away and leaves the young untouched.' },

  // --- алгоритмы (вкладка) ---
  algosTabQuality: { ru: 'Качество алгоритмов: <b>{quality}</b> (данные {data} × команда {team}).', en: 'Algorithm quality: <b>{quality}</b> (data {data} × team {team}).' },
  algosColName: { ru: 'Алгоритм', en: 'Algorithm' },
  algosColProfit: { ru: '₽ / мес', en: '₽ / mo' },
  algosColSubs: { ru: 'Подписчики', en: 'Subscribers' },
  algosColHours: { ru: 'Часы', en: 'Hours' },
  algosTotal: { ru: 'Итого от алгоритмов', en: 'Total from algorithms' },
  algosTeamCost: { ru: 'Стоимость команды', en: 'Cost of the team' },
  algosNet: { ru: 'Чистый эффект', en: 'Net effect' },
  algosCounterfactual: { ru: 'Каждая строка — контрфактический расчёт: прошлый месяц пересчитан заново с выключенным алгоритмом. В реальной компании такой ответ стоит квартала A/B-тестов.', en: 'Every row is a counterfactual: last month was re-simulated with that algorithm switched off. In a real company this answer costs a quarter of A/B testing.' },
  algosNone: { ru: 'Ни один алгоритм не включён — сравнивать нечего. Начните с бюджета на Data Science.', en: 'No algorithm is switched on, so there is nothing to compare. Start with a data science budget.' },
  algosZeroNote: { ru: '{names} сейчас почти ничего не меняет. Это не поломка: часть алгоритмов включается только в своём режиме — календарь релизов бесполезен без премьер, удержание — при низком оттоке.', en: '{names} currently changes almost nothing. That is not a bug: some algorithms only engage in their own regime — pacing is useless without premieres, win-back at low churn.' },
  algosVsSlider: { ru: 'Чем алгоритм отличается от ползунка', en: 'How an algorithm differs from a slider' },
  algosVsSliderText: { ru: 'Ползунок задаёт <b>число</b>: 4 минуты рекламы всем и всегда. Алгоритм задаёт <b>правило</b>: реклама = f(терпимость зрителя), скидка = f(вероятность ухода), битрейт = f(сцены). Правило умеет быть разным для разных людей — поэтому улучшает оба конца компромисса, неразрешимого для одного числа.', en: 'A slider sets a <b>number</b>: four minutes of ads for everyone, always. An algorithm sets a <b>rule</b>: ads = f(viewer tolerance), discount = f(probability of leaving), bitrate = f(scene). A rule can differ between people, which is why it improves both ends of a trade-off a single number cannot resolve.' },

  // --- справка ---
  helpWhatTitle: { ru: 'Что это такое', en: 'What this is' },
  helpWhatText: { ru: 'Вы управляете онлайн-кинотеатром. Один ход — месяц, партия — три года. Цель: построить сервис, который дорого стоит <i>и</i> в котором вам всё ещё принадлежит большая доля.', en: 'You run a streaming service. One turn is a month, a game is three years. The goal: build a service that is worth a lot <i>and</i> in which you still own a large share.' },
  helpCatalogTitle: { ru: 'Каталог: аренда против актива', en: 'Catalogue: renting versus owning' },
  helpCatalogFormula: {
    ru: `лицензии: появляются сразу, истекают 4,5% в месяц, есть у конкурентов
оригиналы: премьера через 6 месяцев, остаются навсегда, только у вас
глубина = насыщение(лицензии × 0.5 + оригиналы × 6)
свежесть = √(новинки / эталон), новинка стареет за ~4 месяца`,
    en: `licences: available at once, expire at 4.5% a month, rivals have them too
originals: premiere in 6 months, stay forever, yours alone
depth = saturation(licensed × 0.5 + originals × 6)
freshness = √(new releases / reference), a release ages out in ~4 months`,
  },
  helpCatalogText: { ru: 'Час собственной премьеры удерживает как несколько часов библиотеки, но стоит в полсотни раз дороже. Ни одна из крайностей не работает: на одних лицензиях нечем удерживать, на одних оригиналах нечего смотреть.', en: 'An hour of your own premiere retains like several hours of library, but costs fifty times more. Neither extreme works: licences alone give you nothing to hold people with, originals alone give them nothing to watch.' },
  helpMoneyTitle: { ru: 'Почему трафик — главное', en: 'Why bandwidth is the thing to watch' },
  helpMoneyText: { ru: 'В подписке выручка с человека фиксирована, а расходы растут вместе с просмотром. Самый лояльный зритель — самый дорогой. Это переворачивает привычную логику: здесь рост вовлечённости надо считать, а не праздновать.', en: 'In a subscription business revenue per person is fixed while cost grows with viewing. Your most loyal viewer is your most expensive one. That inverts the usual logic: here engagement growth is something to calculate, not to celebrate.' },
  helpChurnTitle: { ru: 'Обратные связи, которые вас погубят', en: 'The feedback loops that will kill you' },
  helpSpiralStale: { ru: '<b>Спираль скуки.</b> Нет премьер → растёт отток → падает выручка → режется контентный бюджет → премьер ещё меньше.', en: '<b>The staleness spiral.</b> No premieres → churn rises → revenue falls → the content budget is cut → even fewer premieres.' },
  helpSpiralHangover: { ru: '<b>Синдром сериала.</b> Громкая премьера приводит толпу, которая уходит, досмотрев её. Один хит без продолжения — это заём, а не рост.', en: '<b>The one-show syndrome.</b> A loud premiere brings a crowd that leaves once they have finished it. A single hit with nothing behind it is a loan, not growth.' },
  helpSpiralAds: { ru: '<b>Спираль рекламы.</b> Больше минут → больше выручки сейчас → выше отток → меньше зрителей → меньше показов.', en: '<b>The ad spiral.</b> More minutes → more revenue now → higher churn → fewer viewers → fewer impressions.' },
  helpSpiralTraffic: { ru: '<b>Ловушка вовлечённости.</b> Зритель смотрит больше → лоялен → но трафик дороже подписки, и рост часов съедает маржу.', en: '<b>The engagement trap.</b> Viewers watch more → they are loyal → but bandwidth outruns the subscription and rising hours eat the margin.' },
  helpRivalTitle: { ru: 'Афиша конкурента', en: 'The rival’s line-up' },
  helpRivalText: { ru: 'Чужие премьеры известны за месяц: даты публикуются задолго до выхода. Они забирают приток новых подписок и часть внимания ваших зрителей. Своя громкая премьера в тот же месяц частично гасит чужую — но запускать её в производство нужно было полгода назад.', en: 'Rival premieres are known a month ahead: dates are published long before release. They take away new sign-ups and part of your viewers’ attention. Your own loud premiere in the same month partly blunts theirs — but it had to enter production six months earlier.' },
  helpAlgosTitle: { ru: 'Оптимизации второго порядка', en: 'Second-order optimisation' },
  helpAlgosText: { ru: 'Ползунки задают числа, алгоритмы — правила. Качество = √(данные × команда), и данные здесь — часы просмотра. Поэтому алгоритмы всегда приходят позже контента: рекомендовать нечего, пока нечего смотреть.', en: 'Sliders set numbers, algorithms set rules. Quality = √(data × team), and here the data is watch hours. So algorithms always arrive after content: there is nothing to recommend until there is something to watch.' },
  helpScoreTitle: { ru: 'Как считается финальный счёт', en: 'How the final score works' },
  helpScoreFormula: {
    ru: `оценка = годовая выручка × мультипликатор + библиотека оригиналов
мультипликатор растёт от темпа роста и рентабельности
счёт = оценка × ваша доля`,
    en: `valuation = annual revenue × multiple + your original library
the multiple grows with growth rate and margin
score = valuation × your stake`,
  },
  helpScoreText: { ru: 'Собственная библиотека входит в оценку напрямую — в отличие от лицензий, которые вы всего лишь арендуете. Два сервиса с одинаковой выручкой стоят по-разному.', en: 'Your own library enters the valuation directly, unlike licences, which you merely rent. Two services with identical revenue are worth different amounts.' },
  helpLimitsTitle: { ru: 'Ограничения модели', en: 'Limits of the model' },
  helpLimitsText: { ru: 'Это учебная модель, а не прогноз. Конкурент не реагирует на ваши решения, права не торгуются по отдельности, зрители внутри сегмента одинаковы, а качество проекта — одно число вместо сотни решений съёмочной группы.', en: 'This is a teaching model, not a forecast. The rival does not react to your decisions, rights are not negotiated individually, viewers within a segment are identical, and a project’s quality is one number standing in for a hundred decisions on set.' },

  // --- финал ---
  gameOverBankrupt: { ru: '💀 Деньги кончились', en: '💀 Out of money' },
  gameOverFinished: { ru: '🏁 Три года позади', en: '🏁 Three years done' },
  gameOverBankruptText: { ru: 'Касса ушла в минус на {month}-м месяце. Контент оплачивается вперёд, а окупается через полгода — этот разрыв и топит сервисы.', en: 'Cash went negative in month {month}. Content is paid for upfront and pays back six months later — that gap is what sinks services.' },
  gameOverFinishedText: { ru: 'Тридцать шесть месяцев позади. Итоговая оценка компании и ваша доля в ней:', en: 'Thirty-six months done. Here is the final valuation and your share of it:' },
  scoreValuation: { ru: 'Оценка компании', en: 'Company valuation' },
  scoreStake: { ru: 'Ваша доля', en: 'Your stake' },
  scoreResult: { ru: 'Ваш результат', en: 'Your result' },
  scoreRaised: { ru: 'Привлечено', en: 'Raised' },
  scoreCash: { ru: 'Касса', en: 'Cash' },
  scoreLibrary: { ru: 'Своя библиотека', en: 'Own library' },
  scoreGrade: { ru: 'Оценка результата', en: 'Verdict' },
  gradeBankrupt: { ru: 'Банкротство', en: 'Bankruptcy' },
  gradeExcellent: { ru: 'Отличный результат', en: 'Excellent' },
  gradeSolid: { ru: 'Крепкий сервис', en: 'A solid service' },
  gradeSurvived: { ru: 'Выжили', en: 'Survived' },
  gradeModest: { ru: 'Скромно', en: 'Modest' },
  gameOverLastMonth: { ru: 'Последний месяц: {subs} подписчиков, ARPU {arpu}, отток {churn}, прибыль {profit}.', en: 'Final month: {subs} subscribers, ARPU {arpu}, churn {churn}, profit {profit}.' },
  gameOverQuestions: { ru: '<b>Вопросы для разбора:</b> что удерживало подписчика — каталог или привычка? В какой момент рост часов перестал приносить прибыль? Сколько стоила бы та же база без единого оригинала?', en: '<b>Questions for the debrief:</b> what kept subscribers — the catalogue or the habit? At what point did rising hours stop producing profit? What would the same base be worth without a single original?' },
  gameOverPlayAgain: { ru: 'Сыграть ещё раз', en: 'Play again' },
  // --- Развилка перед смертью и разбор краха ---
  deathTitle: { ru: '⚠️ Деньги на исходе', en: '⚠️ Running out of money' },
  deathText: { ru: 'В кассе {cash}, за прошлый месяц сожгли {burn}. Таким темпом денег хватит примерно на {runway}. Раунд ещё можно поднять — но чем ближе касса к нулю, тем хуже условия. Это предупреждение показывается один раз.', en: 'The till holds {cash}; last month burned {burn}. At this pace the money lasts about {runway}. A round can still be raised — but the closer the till is to zero, the worse the terms. You will only see this warning once.' },
  deathRunway: { ru: '{n} мес.', en: '{n} mo' },
  deathRaise: { ru: 'Поднять {amount} (доля −{dilution})', en: 'Raise {amount} (stake −{dilution})' },
  deathIgnore: { ru: 'Продолжить как есть', en: 'Carry on as is' },
  deathRaised: { ru: 'Раунд закрыт: +{amount} в кассу, доля снизилась до {equity}.', en: 'Round closed: +{amount} in the till, stake now {equity}.' },
  deathWaterfall: { ru: 'Последние месяцы: куда ушли деньги', en: 'The final months: where the money went' },
  wfRevenue: { ru: 'Выручка', en: 'Revenue' },
  wfCosts: { ru: 'Расходы', en: 'Costs' },
  wfProfit: { ru: 'Итог месяца', en: 'Month net' },
  wfCash: { ru: 'Касса на конец', en: 'Cash at end' },
  wfTurn: { ru: 'мес. {n}', en: 'mo {n}' },
  // --- Код партии и таблица рекордов ---
  resultTitle: { ru: 'Строка результата', en: 'Result string' },
  resultNote: { ru: 'Скопируйте и отправьте преподавателю: в строке зашиты код партии, счёт и контрольная сумма.', en: 'Copy it and send it to your teacher: the string carries the game code, the score and a checksum.' },
  resultCopy: { ru: 'Скопировать', en: 'Copy' },
  resultCopied: { ru: 'Строка результата скопирована.', en: 'Result string copied.' },
  recordsTitle: { ru: 'Ваши лучшие партии на этом устройстве', en: 'Your best games on this device' },
  recordsDate: { ru: 'Дата', en: 'Date' },
  recordsCode: { ru: 'Код партии', en: 'Game code' },
  recordsScore: { ru: 'Итог', en: 'Score' },
  recordsOutcome: { ru: 'Исход', en: 'Outcome' },
  recordsOutcomeFinished: { ru: 'финиш', en: 'finished' },
  recordsOutcomeBankrupt: { ru: 'банкрот', en: 'bankrupt' },
  recordsYou: { ru: '← эта партия', en: '← this game' },
  seedLabel: { ru: 'Код партии (необязательно)', en: 'Game code (optional)' },
  seedPlaceholder: { ru: 'например, урок-7б', en: 'e.g. class-7b' },
  seedNote: { ru: 'Одинаковый код — одинаковый рынок у всех, кто его ввёл. Пустое поле — случайный.', en: 'The same code gives everyone the same market. Empty means random.' },
  welcomeBest: { ru: 'Ваш лучший результат на этом устройстве: {score}.', en: 'Your best result on this device: {score}.' },
  // --- Оговорка о числах: одинаковая во всех трёх играх ---
  welcomeNumbers: { ru: '<b>О числах.</b> Модель — из рабочего опыта, числа условные, подобранные для играбельности: не бенчмарки и не данные реальных компаний. Игра иллюстрирует механику связей, а не величины; оценивать по ней настоящий бизнес нельзя.', en: '<b>About the numbers.</b> The model comes from working experience; the numbers are notional, chosen for playability — not benchmarks, not real companies’ data. The game illustrates the mechanics of the relationships, not the magnitudes; it is not a tool for valuing a real business.' },
  footNumbers: { ru: 'Числа в модели условные, не отраслевые бенчмарки: игра иллюстрирует механику связей, а не величины.', en: 'The numbers in the model are notional, not industry benchmarks: the game illustrates the mechanics of the relationships, not the magnitudes.' },
  helpSeed: { ru: 'Код этой партии: <b>{seed}</b> — введите его на экране приветствия, чтобы сыграть тот же рынок ещё раз.', en: 'This game’s code: <b>{seed}</b> — enter it on the welcome screen to play the same market again.' },
  alertHarvest: { ru: '<b>Прибыль при тающей базе — это дожинание, а не рост.</b> За три месяца ушло {lost} подписчиков. Оценка компании платит за рост: сжимающийся сервис стоит дёшево даже в плюсе.', en: '<b>Profit on a melting base is harvesting, not growth.</b> {lost} subscribers left over three months. Valuation pays for growth: a shrinking service is cheap even in the black.' },
  gradeScale: { ru: 'Шкала: «отлично» — итог от {a}, «крепкий бизнес» — от {b}, «выжили» — от {c}. Доведённые стратегии на этом рынке заканчивают партию с сотнями миллиардов — выжить легко, выиграть нет.', en: 'The scale: "excellent" starts at {a}, "a solid business" at {b}, "survived" at {c}. Polished strategies finish this market in the hundreds of billions — surviving is easy, winning is not.' },
  // --- Дневник решений на графике ---
  chartChangesTitle: { ru: 'Пунктир — ваши решения.', en: 'Dashed lines are your decisions.' },
  chartChangeItem: { ru: 'мес. {turn}: {what}', en: 'mo {turn}: {what}' },
  reportDelta: { ru: 'К прошлому месяцу: подписчики {subs}, прибыль {profit}, касса {cash}.', en: 'Versus last month: subscribers {subs}, profit {profit}, cash {cash}.' },
  fundingRunway: { ru: 'При темпе прошлого месяца кассы хватит примерно на {n} мес. Раунд дешевле поднимать заранее, а не у нуля.', en: 'At last month’s pace the till lasts about {n} months. A round is cheaper raised early, not at zero.' },
  gameOverCharts: { ru: 'Посмотреть графики', en: 'Look at the charts' },
  // --- Приветственный экран ---
  welcomeTitle: { ru: '🎬 Вы управляете онлайн-кинотеатром', en: '🎬 You are running a streaming service' },
  welcomeRole: { ru: 'Сервис «КИНОПОТОК» — подписка на кино и сериалы. Вы решаете, что взять у студий, что снять самим, сколько стоит подписка — и что делать, когда конкурент выкатывает громкий сериал.', en: 'KINOPOTOK is a subscription service for films and shows. You decide what to license from studios, what to make yourself, what the subscription costs — and what to do when the rival drops a hit show.' },
  welcomeTurn: { ru: '<b>Один ход — месяц,</b> партия — три года, 36 ходов: принимаете решения, запускаете месяц и читаете, что изменилось.', en: '<b>One turn is a month,</b> a game is three years — 36 turns: make your decisions, run the month and read what changed.' },
  welcomeTension: { ru: '<b>В чём подвох.</b> Подписчик платит одно и то же, а вы — за каждый просмотренный час: чем больше смотрят, тем дороже вам. И время против вас: чужие права истекают, а свой сериал выходит через полгода после оплаты.', en: '<b>Where the catch is.</b> A subscriber pays the same either way, while you pay for every hour watched: the more they watch, the more they cost you. Time is against you too: licensed rights expire, and your own show arrives six months after you pay.' },
  welcomeGoal: { ru: '<b>Проиграть не страшно:</b> растерять подписчиков и понять, с какого решения это началось, — полезнее, чем случайно выжить.', en: '<b>Losing is fine:</b> losing subscribers and seeing which decision started it teaches more than surviving by accident.' },
  welcomeStart: { ru: 'Начать', en: 'Start' },
  welcomeMore: { ru: 'Подробнее', en: 'Details' },
  welcomeHint: { ru: '<b>Первый ход</b> можно сделать, ничего не трогая. У каждого ползунка есть «зачем это?», разбор хода игра пишет сама, подробности — за кнопкой «?».', en: '<b>Your first turn</b> can be played without touching anything. Every slider has a "why does this matter?", the game explains each turn itself, and the "?" button has the rest.' },
  helpModalTitle: { ru: 'Как играть', en: 'How to play' },
  helpModalOk: { ru: 'Понятно', en: 'Got it' },
  helpVersion: { ru: 'Сборка {version} от {date}.', en: 'Build {version}, {date}.' },
  helpAuthor: { ru: 'Игру сделал <b><a href="https://www.linkedin.com/in/ruben-deev" target="_blank" rel="noopener">Ruben Deev</a></b>. Лицензия <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ru" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>: свободно для учёбы и некоммерческого использования с указанием автора.', en: 'Made by <b><a href="https://www.linkedin.com/in/ruben-deev" target="_blank" rel="noopener">Ruben Deev</a></b>. Licensed <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>: free for education and non-commercial use with attribution.' },
  helpVersionDev: { ru: 'Сборка из исходников (не раздаваемый файл).', en: 'Built from source (not a distributed file).' },
  crashTitle: { ru: 'Игра не смогла запуститься', en: 'The game failed to start' },
  crashText: { ru: 'Скорее всего, браузер слишком старый или сохранение осталось от другой версии. Сохранение уже сброшено — попробуйте перезапустить.', en: 'Most likely the browser is too old, or the save is left over from another version. The save has been cleared — try restarting.' },
  crashReset: { ru: 'Перезапустить', en: 'Restart' },
  crashBrowser: { ru: 'Если не помогло — пришлите текст выше: по нему видно, чего не хватает браузеру.', en: 'If that did not help, send the text above: it shows what the browser is missing.' },
  restartTitle: { ru: 'Начать заново?', en: 'Start over?' },
  restartText: { ru: 'Текущая партия будет потеряна, рынок сгенерируется заново.', en: 'The current game will be lost and the market will be regenerated.' },
  restartYes: { ru: 'Да, заново', en: 'Yes, restart' },
  restartNo: { ru: 'Отмена', en: 'Cancel' },
};
