// ============================================================================
// Строки интерфейса игры «КИНОПОТОК». Пары { ru, en }.
// Регистрируются в ядре локализации вызовом setStrings() при старте.
// ============================================================================

export const STRINGS = {
  // --- шапка ---
  brandTitle: { ru: 'КИНОПОТОК', en: 'KINOPOTOK' },
  brandSub: { ru: 'экономический симулятор онлайн-кинотеатра', en: 'streaming service economics simulator' },
  btnRestart: { ru: 'Заново', en: 'Restart' },
  btnHelpTitle: { ru: 'Как играть', en: 'How to play' },
  btnNext: { ru: 'Прожить месяц {month} →', en: 'Run month {month} →' },
  btnResults: { ru: 'Итоги партии', en: 'Final results' },
  langToggle: { ru: 'EN', en: 'RU' },
  langTitle: { ru: 'Switch to English', en: 'Переключить на русский' },

  // --- KPI ---
  kpiMonth: { ru: 'Месяц', en: 'Month' },
  kpiMonthEvent: { ru: '⚡ событие', en: '⚡ event' },
  kpiMonthCalm: { ru: 'обычный месяц', en: 'a quiet month' },
  kpiCash: { ru: 'Касса', en: 'Cash' },
  kpiCashOut: { ru: 'деньги кончились', en: 'out of money' },
  kpiRunway: { ru: 'хватит на {months} мес.', en: '{months} months of runway' },
  kpiProfitable: { ru: 'операционно прибыльны', en: 'operationally profitable' },
  kpiSubs: { ru: 'Подписчики', en: 'Subscribers' },
  kpiSubsSub: { ru: '{premium} платных · {ads} с рекламой', en: '{premium} ad-free · {ads} on ads' },
  kpiRevenue: { ru: 'Выручка / мес', en: 'Revenue / mo' },
  kpiRevenueSub: { ru: 'ARPU {value}', en: 'ARPU {value}' },
  kpiProfit: { ru: 'Прибыль / мес', en: 'Profit / mo' },
  kpiProfitSub: { ru: 'вклад {value}', en: 'contribution {value}' },
  kpiChurn: { ru: 'Отток', en: 'Churn' },
  kpiChurnSub: { ru: 'жизнь подписки {months} мес.', en: 'subscription lasts {months} mo.' },
  kpiHours: { ru: 'Часов на подписчика', en: 'Hours per subscriber' },
  kpiHoursSub: { ru: 'трафик {value}', en: 'bandwidth {value}' },
  kpiEquity: { ru: 'Оценка × доля', en: 'Valuation × stake' },
  kpiEquitySub: { ru: 'ваша доля {value}', en: 'your stake {value}' },
  kpiStart: { ru: 'Старт', en: 'Start' },
  kpiStartSub: { ru: 'деньги инвестора, 100% ваши', en: 'investor money, 100% yours' },

  // --- панели ---
  panelLevers: { ru: 'Рычаги управления', en: 'Business levers' },
  panelStudio: { ru: 'Студия и производство', en: 'Studio and production' },
  panelAlgos: { ru: 'Алгоритмы и данные', en: 'Algorithms and data' },
  panelFunding: { ru: 'Финансирование', en: 'Funding' },
  panelDynamics: { ru: 'Динамика', en: 'Trends' },
  leverWhy: { ru: 'зачем это?', en: 'why does this matter?' },

  // --- сводка под ползунками ---
  opsCatalog: { ru: 'Каталог: <b>{hours}</b> часов ({licensed} лицензий + {original} своих). Глубина <b>{depth}</b>, свежесть <b>{fresh}</b>.', en: 'Catalogue: <b>{hours}</b> hours ({licensed} licensed + {original} original). Depth <b>{depth}</b>, freshness <b>{fresh}</b>.' },
  opsLicensing: { ru: 'Бюджет лицензий купит <b>{hours}</b> часов в месяц, из них истечёт {decay} за месяц.', en: 'The licensing budget buys <b>{hours}</b> hours a month; {decay} of the library expires each month.' },
  opsUnitCheck: { ru: 'Подписчик приносит <b>{arpu}</b> и стоит <b>{cost}</b> трафика и поддержки → вклад <b class="{cls}">{cm}</b>.', en: 'A subscriber brings <b>{arpu}</b> and costs <b>{cost}</b> in bandwidth and support → contribution <b class="{cls}">{cm}</b>.' },
  opsAdShare: { ru: 'На дешёвый тариф уходит примерно <b>{share}</b> подписчиков — они платят меньше, но приносят рекламу.', en: 'Roughly <b>{share}</b> of subscribers pick the cheap tier — they pay less but bring advertising.' },

  // --- студия ---
  studioGenre: { ru: 'Во что вкладывается студия', en: 'What the studio is making' },
  studioProject: { ru: 'Проект стоит {cost} и выйдет через {months} мес.', en: 'A project costs {cost} and premieres in {months} months.' },
  studioFund: { ru: 'Накоплено на текущий проект: <b>{fund}</b> из {cost}.', en: 'Saved towards the current project: <b>{fund}</b> of {cost}.' },
  studioPipelineEmpty: { ru: 'В производстве ничего нет. Премьеры не будет — а значит, не будет и причины подписаться.', en: 'Nothing is in production. There will be no premiere — and therefore no reason to subscribe.' },
  studioPipeline: { ru: 'В производстве: {list}.', en: 'In production: {list}.' },
  studioPipelineItem: { ru: '{genre} через {months} мес.', en: '{genre} in {months} mo.' },
  studioLag: { ru: 'Деньги уходят сегодня, зритель увидит результат через полгода. Решение о премьере вы принимаете сейчас — вслепую.', en: 'The money goes out today and viewers see the result in six months. You are deciding about that premiere now, blind.' },

  // --- афиша конкурента ---
  rivalPanel: { ru: 'Афиша конкурента · {season}, месяц {month}', en: 'Rival line-up · {season}, month {month}' },
  rivalNow: { ru: 'этот месяц', en: 'this month' },
  rivalNext: { ru: 'анонсировано на следующий', en: 'announced for next month' },
  rivalNone: { ru: 'Тихо', en: 'Quiet' },
  rivalSmall: { ru: 'Проходной релиз', en: 'Minor release' },
  rivalNotable: { ru: 'Заметная премьера', en: 'Notable premiere' },
  rivalMajor: { ru: 'Крупная премьера', en: 'Major premiere' },
  rivalMega: { ru: 'Событие года', en: 'Event of the year' },
  rivalNoEffect: { ru: 'ничего не отвлекает зрителя', en: 'nothing is competing for attention' },
  rivalEffects: { ru: 'приток новых <b class="down">{acq}</b>, отток <b class="down">+{churn} п.п.</b>, часы <b class="down">{hours}</b>', en: 'new sign-ups <b class="down">{acq}</b>, churn <b class="down">+{churn} pp</b>, hours <b class="down">{hours}</b>' },
  rivalAdvice: { ru: 'В следующем месяце зрителя будут звать в другое место. Своя громкая премьера гасит чужую — но её нужно было запустить в производство полгода назад. Что можно сейчас: усилить маркетинг или переждать и не жечь бюджет впустую.', en: 'Next month someone else will be calling your viewers away. Your own loud premiere blunts theirs — but it had to enter production six months ago. What you can still do: push marketing, or sit it out and not burn the budget for nothing.' },

  seasonWinter: { ru: 'зима', en: 'winter' },
  seasonSpring: { ru: 'весна', en: 'spring' },
  seasonSummer: { ru: 'лето', en: 'summer' },
  seasonAutumn: { ru: 'осень', en: 'autumn' },

  // --- алгоритмы ---
  algoData: { ru: 'Данные', en: 'Data' },
  algoTeam: { ru: 'Команда', en: 'Team' },
  algoQuality: { ru: 'Качество', en: 'Quality' },
  algoDataHint: { ru: 'Накопленные часы просмотра — обучающая выборка', en: 'Accumulated watch hours — your training set' },
  algoTeamHint: { ru: 'Накопленные вложения в data science', en: 'Cumulative investment in data science' },
  algoQualityHint: { ru: 'Среднее геометрическое: нужно и то и другое', en: 'Geometric mean: you need both halves' },
  algoIntro: { ru: 'Качество алгоритмов = √(данные × команда). Часы просмотра приходят только от подписчиков, поэтому рекомендации нельзя построить раньше, чем появится кому рекомендовать.', en: 'Algorithm quality = √(data × team). Watch hours only come from subscribers, so you cannot build recommendations before there is somebody to recommend to.' },
  algoInstalled: { ru: 'внедрён', en: 'live' },
  algoInstallCost: { ru: 'внедрение {cost}', en: 'rollout {cost}' },
  algoNeedQuality: { ru: 'нужно качество {value}', en: 'needs quality {value}' },
  algoPending: { ru: 'Будет внедрён при переходе к следующему месяцу: разовые {cost}.', en: 'Will be rolled out when you run the next month: a one-off {cost}.' },

  // --- финансирование ---
  fundingTake: { ru: 'Взять', en: 'Take it' },
  fundingDilution: { ru: 'размытие {dilution} → ваша доля {equity}', en: 'dilution {dilution} → your stake {equity}' },
  fundingHead: { ru: 'Оценка компании: <b>{valuation}</b> (pre-money). Ваша доля: <b>{equity}</b>, привлечено: {raised}.', en: 'Company valuation: <b>{valuation}</b> (pre-money). Your stake: <b>{equity}</b>, raised so far: {raised}.' },
  fundingNote: { ru: 'В оценку входит и собственная библиотека: оригиналы — актив, лицензии — аренда. Поэтому два сервиса с одинаковой выручкой стоят по-разному.', en: 'The valuation includes your own library: originals are an asset, licences are rent. That is why two services with identical revenue are worth different amounts.' },
  fundingLocked: { ru: '<br><b>Раунд доступен с {month}-го месяца.</b>', en: '<br><b>Rounds open from month {month}.</b>' },
  fundingDone: { ru: 'Раунд закрыт: {amount} за {dilution} компании.', en: 'Round closed: {amount} for {dilution} of the company.' },

  // --- события ---
  eventAuto: { ru: 'Событие сработает автоматически при переходе к следующему месяцу.', en: 'This event resolves automatically when you run the next month.' },
  eventLesson: { ru: 'Экономический смысл:', en: 'What this teaches:' },
  eventChoiceNeeded: { ru: 'Сначала выберите решение по событию месяца.', en: 'Choose how to handle this month’s event first.' },

  // --- отчёт ---
  reportMonth0: { ru: 'Месяц 0. Сервис ещё не запущен.', en: 'Month 0. The service has not launched yet.' },
  reportStartTitle: { ru: 'С чего начать.', en: 'Where to start.' },
  reportStartIntro: { ru: 'У вас {cash} и библиотека из нескольких сотен часов старого кино. Порядок почти всегда такой:', en: 'You have {cash} and a library of a few hundred hours of old films. The sequence is almost always this:' },
  reportStart1: { ru: 'Включите <b>закупку лицензий</b>: каталог нужен прямо сейчас, а собственный проект выйдет только через полгода.', en: 'Turn on <b>licensing</b>: you need a catalogue right now, and your own project will not premiere for six months.' },
  reportStart2: { ru: 'Одновременно запустите <b>производство</b>. Оригинал — единственное, чего нет у конкурента, и он остаётся вашим навсегда.', en: 'At the same time start <b>production</b>. An original is the only thing your rival does not have, and it stays yours forever.' },
  reportStart3: { ru: 'Проверьте вклад с подписчика: трафик растёт вместе с просмотром, и слишком щедрый битрейт съедает подписку целиком.', en: 'Check contribution per subscriber: bandwidth grows with viewing, and an over-generous bitrate can swallow the whole subscription fee.' },
  reportStart4: { ru: 'Только потом включайте <b>маркетинг</b>. Приводить зрителя в пустой каталог — самый дорогой способ купить отток.', en: 'Only then turn on <b>marketing</b>. Bringing viewers into an empty catalogue is the most expensive way to buy churn.' },
  reportStartAlgos: { ru: '<b>Алгоритмы</b> откроются позже: им нужны часы просмотра, а часы приходят только от подписчиков.', en: '<b>Algorithms</b> unlock later: they need watch hours, and hours only come from subscribers.' },
  reportTitle: { ru: 'Итоги месяца {month}', en: 'Month {month} results' },
  reportHeadStats: { ru: 'выручка {revenue} · подписка {subscription} · реклама {ads}', en: 'revenue {revenue} · subscriptions {subscription} · advertising {ads}' },

  statSubs: { ru: 'Подписчики', en: 'Subscribers' },
  statSubsSub: { ru: '+{gained} / −{lost}', en: '+{gained} / −{lost}' },
  statHours: { ru: 'Часы просмотра', en: 'Watch hours' },
  statHoursSub: { ru: '{perSub} ч на подписчика', en: '{perSub} h per subscriber' },
  unitHours: { ru: 'ч', en: 'h' },
  genreHours: { ru: '{hours} ч контента', en: '{hours} h of content' },
  statCatalog: { ru: 'Каталог', en: 'Catalogue' },
  statCatalogSub: { ru: 'своих {original} ч ({share})', en: '{original} h original ({share})' },
  statFresh: { ru: 'Свежесть', en: 'Freshness' },
  statFreshSub: { ru: 'глубина ×{depth}', en: 'depth ×{depth}' },
  statChurn: { ru: 'Отток', en: 'Churn' },
  statChurnSub: { ru: 'после премьеры +{hangover}', en: 'post-premiere +{hangover}' },
  statArpu: { ru: 'ARPU', en: 'ARPU' },
  statArpuSub: { ru: 'вклад {value}', en: 'contribution {value}' },
  statTraffic: { ru: 'Трафик', en: 'Bandwidth' },
  statTrafficSub: { ru: '{perHour} ₽ за час', en: '₽{perHour} per hour' },
  statProfit: { ru: 'Прибыль', en: 'Profit' },
  statProfitSub: { ru: 'постоянные {value}', en: 'fixed costs {value}' },
  statCacLtv: { ru: 'CAC / LTV', en: 'CAC / LTV' },
  statCacOff: { ru: 'маркетинг выключен', en: 'marketing is off' },

  premiereNote: { ru: 'Премьера: {list}. Шум привёл подписчиков — но через месяц те, кто пришёл только ради неё, начнут уходить.', en: 'Premiere: {list}. The buzz brought subscribers in — but a month from now the ones who came only for it will start leaving.' },
  premiereItem: { ru: '{genre} (качество {quality})', en: '{genre} (quality {quality})' },
  startedNote: { ru: 'Запущено в производство: {list}. Премьера через {months} мес.', en: 'Entered production: {list}. Premiere in {months} months.' },
  installNote: { ru: 'Внедрено: {names} — разовые {cost}.', en: 'Rolled out: {names} — a one-off {cost}.' },

  driversTitle: { ru: 'Почему база подписчиков изменилась ({delta})', en: 'Why the subscriber base changed ({delta})' },
  driverPrice: { ru: 'Цена подписки', en: 'Subscription price' },
  driverCatalog: { ru: 'Каталог и новинки', en: 'Catalogue and new releases' },
  driverAds: { ru: 'Рекламная нагрузка', en: 'Ad load' },
  driverRival: { ru: 'Премьеры конкурента', en: 'Rival premieres' },
  driverRetention: { ru: 'Удержание', en: 'Retention' },
  driverAwareness: { ru: 'Узнаваемость и маркетинг', en: 'Awareness and marketing' },

  // --- предупреждения ---
  alertNoCatalog: { ru: 'Каталог почти пуст: глубина ×{depth}. Приводить зрителя некуда — маркетинг сейчас сгорает впустую.', en: 'The catalogue is nearly empty: depth ×{depth}. There is nowhere to bring viewers — marketing simply burns right now.' },
  alertStale: { ru: 'Новинок нет: свежесть ×{fresh}. Каталог не стал меньше, но зритель видит одно и то же и уходит — за месяц {lost}.', en: 'No new releases: freshness ×{fresh}. The catalogue has not shrunk, but viewers see the same shelf and leave — {lost} this month.' },
  alertNoPipeline: { ru: 'В производстве пусто. Через полгода у вас не будет ни одной премьеры, и остановить отток будет нечем.', en: 'Production is empty. In six months you will have no premiere at all and nothing to stop the churn with.' },
  alertNegativeCm: { ru: 'Вклад с подписчика отрицательный ({value}). Каждый новый зритель увеличивает убыток: трафик дороже подписки.', en: 'Contribution per subscriber is negative ({value}). Every new viewer deepens the loss: bandwidth costs more than the subscription.' },
  alertTrafficHeavy: { ru: 'Трафик съедает {share} выручки ({cost}). При {hours} ч на подписчика битрейт {bitrate} Мбит/с — дорогое удовольствие.', en: 'Bandwidth eats {share} of revenue ({cost}). At {hours} h per subscriber, {bitrate} Mbps is an expensive luxury.' },
  alertBreakEven: { ru: 'Вклад с подписчика {cm}, постоянных расходов на {fixed}. Точка безубыточности: {subs} подписчиков.', en: 'Contribution per subscriber is {cm} against {fixed} of fixed costs. Break-even sits at {subs} subscribers.' },
  alertRunway: { ru: 'Денег на {months} месяцев при текущем сжигании {burn}/мес. Контентные бюджеты — первое, что придётся резать.', en: '{months} months of cash left at the current burn of {burn}/mo. Content budgets are the first thing you will have to cut.' },
  alertHangover: { ru: 'Волна отписок после премьеры: отток вырос до {churn}. Те, кто пришёл ради одного сериала, уходят, досмотрев его.', en: 'A post-premiere wave: churn is up to {churn}. Everyone who came for one show leaves once they have finished it.' },
  alertRivalAhead: { ru: 'В следующем месяце у конкурента {release}. Приток новых упадёт примерно до {acq} — либо отвечайте премьерой, либо не тратьте маркетинг впустую.', en: 'Next month the rival has {release}. New sign-ups will fall to about {acq} — either answer with a premiere or do not waste marketing.' },
  alertAdHeavy: { ru: 'Реклама {load} мин/час приносит {revenue}, но поднимает отток. Киноманы уходят от неё втрое быстрее молодёжи.', en: 'An ad load of {load} min/hr brings {revenue} but lifts churn. Cinephiles leave over it three times faster than young viewers.' },
  alertLtvCacBad: { ru: 'LTV/CAC = {value}: подписчик не отобьёт стоимость своего привлечения.', en: 'LTV/CAC = {value}: a subscriber will not repay the cost of acquiring them.' },
  alertLtvCacGood: { ru: 'LTV/CAC = {value} — привлечение окупается с запасом, есть смысл давить на маркетинг.', en: 'LTV/CAC = {value} — acquisition pays back with room to spare, so it is worth pushing marketing.' },
  alertRndIdle: { ru: 'Data Science стоит {cost}/мес, но ни один алгоритм не включён. Команда копит качество ({quality}), а деньги делают только внедрённые правила.', en: 'Data science costs {cost}/mo but no algorithm is switched on. The team is building quality ({quality}); only deployed rules make money.' },
  alertAlgosReady: { ru: 'Доступно к внедрению: {names}. Качество алгоритмов {quality}.', en: 'Ready to roll out: {names}. Algorithm quality is {quality}.' },
  alertProfit: { ru: 'Месяц закрыт в плюс: {value}.', en: 'The month closed in the black: {value}.' },

  // --- графики ---
  chartSubs: { ru: 'Подписчики', en: 'Subscribers' },
  chartSubsCaption: { ru: 'База подписчиков — запас. Приток даёт маркетинг и премьеры, отток — скука и цена. Разница между линиями и есть ваш рост.', en: 'The subscriber base is a stock. Inflow comes from marketing and premieres, outflow from boredom and price. The gap between the lines is your growth.' },
  seriesSubs: { ru: 'Всего', en: 'Total' },
  seriesPremium: { ru: 'Без рекламы', en: 'Ad-free' },
  seriesAds: { ru: 'С рекламой', en: 'Ad tier' },
  chartMoney: { ru: 'Деньги', en: 'Money' },
  chartMoneyCaption: { ru: 'Вклад = выручка − трафик и поддержка. Прибыль = вклад − контент, маркетинг и офис. Контент здесь постоянные расходы: они не зависят от числа зрителей.', en: 'Contribution = revenue − bandwidth and support. Profit = contribution − content, marketing and overheads. Content is a fixed cost here: it does not depend on how many people watch.' },
  seriesRevenue: { ru: 'Выручка', en: 'Revenue' },
  seriesContribution: { ru: 'Вклад', en: 'Contribution' },
  seriesProfit: { ru: 'Прибыль', en: 'Profit' },
  chartCash: { ru: 'Касса', en: 'Cash' },
  chartCashCaption: { ru: 'Контентные бюджеты уходят каждый месяц, а премьера окупается через полгода. Между этими двумя фактами и живёт касса.', en: 'Content budgets go out every month while a premiere pays back six months later. Your cash lives in the gap between those two facts.' },
  chartCatalog: { ru: 'Каталог', en: 'Catalogue' },
  chartCatalogCaption: { ru: 'Лицензии истекают каждый месяц: чтобы каталог просто не уменьшался, платить нужно постоянно. Оригиналы не истекают никогда.', en: 'Licences expire every month: keeping the catalogue merely level requires paying forever. Originals never expire.' },
  seriesLicensed: { ru: 'Лицензии, ч', en: 'Licensed, h' },
  seriesOriginal: { ru: 'Свои, ч', en: 'Original, h' },
  chartEngagement: { ru: 'Просмотр', en: 'Engagement' },
  chartEngagementCaption: { ru: 'Часы на подписчика — одновременно лучший индикатор лояльности и крупнейшая статья переменных расходов. Радоваться им нужно осторожно.', en: 'Hours per subscriber is at once your best loyalty indicator and your largest variable cost. Enjoy it carefully.' },
  seriesHoursPerSub: { ru: 'Часов на подписчика', en: 'Hours per subscriber' },
  seriesChurn: { ru: 'Отток, %', en: 'Churn, %' },
  chartUnit: { ru: 'Юнит', en: 'Unit' },
  chartUnitCaption: { ru: 'ARPU против вклада: разница между ними — трафик и поддержка. Чем больше смотрят, тем шире эта щель.', en: 'ARPU against contribution: the gap between them is bandwidth and support. The more people watch, the wider it gets.' },
  seriesArpu: { ru: 'ARPU, ₽', en: 'ARPU, ₽' },
  seriesCmPerSub: { ru: 'Вклад с подписчика, ₽', en: 'Contribution per subscriber, ₽' },
  chartAlgos: { ru: 'Алгоритмы', en: 'Algorithms' },
  chartAlgosCaption: { ru: 'Качество алгоритмов = √(данные × команда). Данные копятся только от часов просмотра, поэтому кривая всегда отстаёт от роста базы.', en: 'Algorithm quality = √(data × team). Data only accumulates from watch hours, so the curve always lags behind the base.' },
  seriesQuality: { ru: 'Качество, %', en: 'Quality, %' },
  seriesData: { ru: 'Данные, %', en: 'Data, %' },
  seriesTeam: { ru: 'Команда, %', en: 'Team, %' },

  // --- вкладки ---
  tabUnit: { ru: 'Юнит-экономика', en: 'Unit economics' },
  tabPnl: { ru: 'P&L', en: 'P&L' },
  tabAlgos: { ru: 'Алгоритмы', en: 'Algorithms' },
  tabSegments: { ru: 'Аудитория', en: 'Audience' },
  tabHelp: { ru: 'Справка', en: 'Guide' },

  // --- юнит-экономика ---
  unitIntro: { ru: 'Экономика одного подписчика в месяц при текущих настройках — пересчитывается мгновенно, до перехода к следующему месяцу.', en: 'The economics of one subscriber per month at your current settings — recalculated instantly, before you run the next month.' },
  unitColItem: { ru: 'Статья', en: 'Line' },
  unitColPerSub: { ru: '₽ / подписчик', en: '₽ / subscriber' },
  unitSubscription: { ru: 'Подписка', en: 'Subscription' },
  unitAdvertising: { ru: 'Реклама', en: 'Advertising' },
  unitRevenue: { ru: 'ARPU (выручка с подписчика)', en: 'ARPU (revenue per subscriber)' },
  unitCdn: { ru: 'Трафик ({hours} ч × {perHour} ₽)', en: 'Bandwidth ({hours} h × ₽{perHour})' },
  unitSupport: { ru: 'Поддержка и биллинг', en: 'Support and billing' },
  unitContribution: { ru: 'Вклад с подписчика', en: 'Contribution per subscriber' },
  unitNote: { ru: 'Обратите внимание: контента в этой таблице нет. Он не переменный расход — он постоянный, и потому определяет не выгодность подписчика, а необходимый масштаб.', en: 'Note what is missing: content. It is not a variable cost but a fixed one, so it does not decide whether a subscriber is worth having — it decides what scale you need.' },
  unitBreakEven: { ru: 'При постоянных расходах {fixed}/мес точка безубыточности — <b>{subs} подписчиков</b> (сейчас {current}).', en: 'At fixed costs of {fixed}/mo, break-even is <b>{subs} subscribers</b> (currently {current}).' },
  unitNoBreakEven: { ru: 'Вклад с подписчика ≤ 0: точки безубыточности не существует ни при каком масштабе. Сначала чините экономику, потом растите.', en: 'Contribution per subscriber is ≤ 0, so break-even does not exist at any scale. Fix the economics first, then grow.' },
  unitAcquisition: { ru: 'Привлечение подписчика', en: 'Subscriber acquisition' },
  unitCac: { ru: 'CAC (маркетинг / новые подписчики)', en: 'CAC (marketing / new subscribers)' },
  unitLifetime: { ru: 'Срок жизни подписки', en: 'Subscription lifetime' },
  unitLifetimeValue: { ru: '{value} мес.', en: '{value} mo.' },
  unitLtv: { ru: 'LTV (вклад за всё время жизни)', en: 'LTV (lifetime contribution)' },
  unitLtvCacNote: { ru: 'Ориентир индустрии: LTV/CAC ≥ 3. В стриминге эта величина обманчива: она не учитывает контент, без которого подписчик не остался бы ни на месяц.', en: 'The industry benchmark is LTV/CAC ≥ 3. In streaming the number is deceptive: it ignores the content without which the subscriber would not have stayed a single month.' },

  // --- P&L ---
  pnlEmpty: { ru: 'Отчёт появится после первого прожитого месяца.', en: 'The statement appears after your first completed month.' },
  pnlSubscription: { ru: 'Выручка от подписки', en: 'Subscription revenue' },
  pnlAds: { ru: 'Выручка от рекламы', en: 'Advertising revenue' },
  pnlRevenue: { ru: 'Выручка', en: 'Revenue' },
  pnlCdn: { ru: 'Трафик', en: 'Bandwidth' },
  pnlSupport: { ru: 'Поддержка и биллинг', en: 'Support and billing' },
  pnlWinback: { ru: 'Удерживающие скидки', en: 'Retention discounts' },
  pnlContribution: { ru: 'Вклад (contribution)', en: 'Contribution' },
  pnlLicensing: { ru: 'Закупка лицензий', en: 'Licensing' },
  pnlOriginals: { ru: 'Производство оригиналов', en: 'Originals production' },
  pnlMarketing: { ru: 'Маркетинг', en: 'Marketing' },
  pnlTech: { ru: 'Технологии', en: 'Technology' },
  pnlRnd: { ru: 'Data Science', en: 'Data science' },
  pnlHq: { ru: 'Студия, редакция, офис', en: 'Studio, editorial, overheads' },
  pnlOperatingProfit: { ru: 'Операционная прибыль', en: 'Operating profit' },
  pnlOneOff: { ru: 'Разовые расходы (внедрения, события)', en: 'One-off costs (rollouts, events)' },
  pnlCashChange: { ru: 'Изменение кассы', en: 'Change in cash' },
  pnlNote: { ru: 'Контент стоит одинаково при десяти тысячах подписчиков и при десяти миллионах. Именно поэтому стриминг — бизнес масштаба, а не бизнес маржи.', en: 'Content costs the same with ten thousand subscribers as with ten million. That is exactly why streaming is a scale business rather than a margin business.' },

  // --- аудитория ---
  segmentsEmpty: { ru: 'Данные появятся после первого месяца.', en: 'Data appears after the first month.' },
  colSegment: { ru: 'Сегмент', en: 'Segment' },
  colSubs: { ru: 'Подписчики', en: 'Subscribers' },
  colAdShare: { ru: 'С рекламой', en: 'On ads' },
  colChurn: { ru: 'Отток', en: 'Churn' },
  colArpu: { ru: 'ARPU', en: 'ARPU' },
  colPenetration: { ru: 'Охват', en: 'Reach' },
  colPriceFactor: { ru: 'Цена ×', en: 'Price ×' },
  colAppeal: { ru: 'Каталог ×', en: 'Catalogue ×' },
  colAdPenalty: { ru: 'Реклама ×', en: 'Ads ×' },
  segmentsNote: { ru: 'Один и тот же рычаг работает в сегментах по-разному: рубль цены пугает молодёжь и не замечается киноманами, а минута рекламы прогоняет киноманов и не трогает молодёжь.', en: 'The same lever behaves differently by segment: a rouble of price scares young viewers and goes unnoticed by cinephiles, while a minute of advertising drives cinephiles away and leaves the young untouched.' },

  // --- алгоритмы (вкладка) ---
  algosTabQuality: { ru: 'Качество алгоритмов: <b>{quality}</b> (данные {data} × команда {team}).', en: 'Algorithm quality: <b>{quality}</b> (data {data} × team {team}).' },
  algosColName: { ru: 'Алгоритм', en: 'Algorithm' },
  algosColProfit: { ru: '₽ / мес', en: '₽ / mo' },
  algosColSubs: { ru: 'Подписчики', en: 'Subscribers' },
  algosColHours: { ru: 'Часы', en: 'Hours' },
  algosTotal: { ru: 'Итого от алгоритмов', en: 'Total from algorithms' },
  algosTeamCost: { ru: 'Стоимость команды', en: 'Cost of the team' },
  algosNet: { ru: 'Чистый эффект', en: 'Net effect' },
  algosCounterfactual: { ru: 'Каждая строка — контрфактический расчёт: прошлый месяц пересчитан заново с выключенным алгоритмом. В реальной компании такой ответ стоит квартала A/B-тестов.', en: 'Every row is a counterfactual: last month was re-simulated with that algorithm switched off. In a real company this answer costs a quarter of A/B testing.' },
  algosNone: { ru: 'Ни один алгоритм не включён — сравнивать нечего. Начните с бюджета на Data Science.', en: 'No algorithm is switched on, so there is nothing to compare. Start with a data science budget.' },
  algosZeroNote: { ru: '{names} сейчас почти ничего не меняет. Это не поломка: часть алгоритмов включается только в своём режиме — календарь релизов бесполезен без премьер, удержание — при низком оттоке.', en: '{names} currently changes almost nothing. That is not a bug: some algorithms only engage in their own regime — pacing is useless without premieres, win-back at low churn.' },
  algosVsSlider: { ru: 'Чем алгоритм отличается от ползунка', en: 'How an algorithm differs from a slider' },
  algosVsSliderText: { ru: 'Ползунок задаёт <b>число</b>: 4 минуты рекламы всем и всегда. Алгоритм задаёт <b>правило</b>: реклама = f(терпимость зрителя), скидка = f(вероятность ухода), битрейт = f(сцены). Правило умеет быть разным для разных людей — поэтому улучшает оба конца компромисса, неразрешимого для одного числа.', en: 'A slider sets a <b>number</b>: four minutes of ads for everyone, always. An algorithm sets a <b>rule</b>: ads = f(viewer tolerance), discount = f(probability of leaving), bitrate = f(scene). A rule can differ between people, which is why it improves both ends of a trade-off a single number cannot resolve.' },

  // --- справка ---
  helpWhatTitle: { ru: 'Что это такое', en: 'What this is' },
  helpWhatText: { ru: 'Вы управляете онлайн-кинотеатром. Один ход — месяц, партия — три года. Цель: построить сервис, который дорого стоит <i>и</i> в котором вам всё ещё принадлежит большая доля.', en: 'You run a streaming service. One turn is a month, a game is three years. The goal: build a service that is worth a lot <i>and</i> in which you still own a large share.' },
  helpCatalogTitle: { ru: 'Каталог: аренда против актива', en: 'Catalogue: renting versus owning' },
  helpCatalogFormula: {
    ru: `лицензии: появляются сразу, истекают 4,5% в месяц, есть у конкурентов
оригиналы: премьера через 6 месяцев, остаются навсегда, только у вас
глубина = насыщение(лицензии × 0.5 + оригиналы × 6)
свежесть = √(новинки / эталон), новинка стареет за ~4 месяца`,
    en: `licences: available at once, expire at 4.5% a month, rivals have them too
originals: premiere in 6 months, stay forever, yours alone
depth = saturation(licensed × 0.5 + originals × 6)
freshness = √(new releases / reference), a release ages out in ~4 months`,
  },
  helpCatalogText: { ru: 'Час собственной премьеры удерживает как несколько часов библиотеки, но стоит в полсотни раз дороже. Ни одна из крайностей не работает: на одних лицензиях нечем удерживать, на одних оригиналах нечего смотреть.', en: 'An hour of your own premiere retains like several hours of library, but costs fifty times more. Neither extreme works: licences alone give you nothing to hold people with, originals alone give them nothing to watch.' },
  helpMoneyTitle: { ru: 'Почему трафик — главное', en: 'Why bandwidth is the thing to watch' },
  helpMoneyText: { ru: 'В подписке выручка с человека фиксирована, а расходы растут вместе с просмотром. Самый лояльный зритель — самый дорогой. Это переворачивает привычную логику: здесь рост вовлечённости надо считать, а не праздновать.', en: 'In a subscription business revenue per person is fixed while cost grows with viewing. Your most loyal viewer is your most expensive one. That inverts the usual logic: here engagement growth is something to calculate, not to celebrate.' },
  helpChurnTitle: { ru: 'Обратные связи, которые вас погубят', en: 'The feedback loops that will kill you' },
  helpSpiralStale: { ru: '<b>Спираль скуки.</b> Нет премьер → растёт отток → падает выручка → режется контентный бюджет → премьер ещё меньше.', en: '<b>The staleness spiral.</b> No premieres → churn rises → revenue falls → the content budget is cut → even fewer premieres.' },
  helpSpiralHangover: { ru: '<b>Синдром сериала.</b> Громкая премьера приводит толпу, которая уходит, досмотрев её. Один хит без продолжения — это заём, а не рост.', en: '<b>The one-show syndrome.</b> A loud premiere brings a crowd that leaves once they have finished it. A single hit with nothing behind it is a loan, not growth.' },
  helpSpiralAds: { ru: '<b>Спираль рекламы.</b> Больше минут → больше выручки сейчас → выше отток → меньше зрителей → меньше показов.', en: '<b>The ad spiral.</b> More minutes → more revenue now → higher churn → fewer viewers → fewer impressions.' },
  helpSpiralTraffic: { ru: '<b>Ловушка вовлечённости.</b> Зритель смотрит больше → лоялен → но трафик дороже подписки, и рост часов съедает маржу.', en: '<b>The engagement trap.</b> Viewers watch more → they are loyal → but bandwidth outruns the subscription and rising hours eat the margin.' },
  helpRivalTitle: { ru: 'Афиша конкурента', en: 'The rival’s line-up' },
  helpRivalText: { ru: 'Чужие премьеры известны за месяц: даты публикуются задолго до выхода. Они забирают приток новых подписок и часть внимания ваших зрителей. Своя громкая премьера в тот же месяц частично гасит чужую — но запускать её в производство нужно было полгода назад.', en: 'Rival premieres are known a month ahead: dates are published long before release. They take away new sign-ups and part of your viewers’ attention. Your own loud premiere in the same month partly blunts theirs — but it had to enter production six months earlier.' },
  helpAlgosTitle: { ru: 'Оптимизации второго порядка', en: 'Second-order optimisation' },
  helpAlgosText: { ru: 'Ползунки задают числа, алгоритмы — правила. Качество = √(данные × команда), и данные здесь — часы просмотра. Поэтому алгоритмы всегда приходят позже контента: рекомендовать нечего, пока нечего смотреть.', en: 'Sliders set numbers, algorithms set rules. Quality = √(data × team), and here the data is watch hours. So algorithms always arrive after content: there is nothing to recommend until there is something to watch.' },
  helpScoreTitle: { ru: 'Как считается финальный счёт', en: 'How the final score works' },
  helpScoreFormula: {
    ru: `оценка = годовая выручка × мультипликатор + библиотека оригиналов
мультипликатор растёт от темпа роста и рентабельности
счёт = оценка × ваша доля`,
    en: `valuation = annual revenue × multiple + your original library
the multiple grows with growth rate and margin
score = valuation × your stake`,
  },
  helpScoreText: { ru: 'Собственная библиотека входит в оценку напрямую — в отличие от лицензий, которые вы всего лишь арендуете. Два сервиса с одинаковой выручкой стоят по-разному.', en: 'Your own library enters the valuation directly, unlike licences, which you merely rent. Two services with identical revenue are worth different amounts.' },
  helpLimitsTitle: { ru: 'Ограничения модели', en: 'Limits of the model' },
  helpLimitsText: { ru: 'Это учебная модель, а не прогноз. Конкурент не реагирует на ваши решения, права не торгуются по отдельности, зрители внутри сегмента одинаковы, а качество проекта — одно число вместо сотни решений съёмочной группы.', en: 'This is a teaching model, not a forecast. The rival does not react to your decisions, rights are not negotiated individually, viewers within a segment are identical, and a project’s quality is one number standing in for a hundred decisions on set.' },

  // --- финал ---
  gameOverBankrupt: { ru: '💀 Деньги кончились', en: '💀 Out of money' },
  gameOverFinished: { ru: '🏁 Три года позади', en: '🏁 Three years done' },
  gameOverBankruptText: { ru: 'Касса ушла в минус на {month}-м месяце. Контент оплачивается вперёд, а окупается через полгода — этот разрыв и топит сервисы.', en: 'Cash went negative in month {month}. Content is paid for upfront and pays back six months later — that gap is what sinks services.' },
  gameOverFinishedText: { ru: 'Тридцать шесть месяцев позади. Итоговая оценка компании и ваша доля в ней:', en: 'Thirty-six months done. Here is the final valuation and your share of it:' },
  scoreValuation: { ru: 'Оценка компании', en: 'Company valuation' },
  scoreStake: { ru: 'Ваша доля', en: 'Your stake' },
  scoreResult: { ru: 'Ваш результат', en: 'Your result' },
  scoreRaised: { ru: 'Привлечено', en: 'Raised' },
  scoreCash: { ru: 'Касса', en: 'Cash' },
  scoreLibrary: { ru: 'Своя библиотека', en: 'Own library' },
  scoreGrade: { ru: 'Оценка результата', en: 'Verdict' },
  gradeBankrupt: { ru: 'Банкротство', en: 'Bankruptcy' },
  gradeExcellent: { ru: 'Отличный результат', en: 'Excellent' },
  gradeSolid: { ru: 'Крепкий сервис', en: 'A solid service' },
  gradeSurvived: { ru: 'Выжили', en: 'Survived' },
  gradeModest: { ru: 'Скромно', en: 'Modest' },
  gameOverLastMonth: { ru: 'Последний месяц: {subs} подписчиков, ARPU {arpu}, отток {churn}, прибыль {profit}.', en: 'Final month: {subs} subscribers, ARPU {arpu}, churn {churn}, profit {profit}.' },
  gameOverQuestions: { ru: '<b>Вопросы для разбора:</b> что удерживало подписчика — каталог или привычка? В какой момент рост часов перестал приносить прибыль? Сколько стоила бы та же база без единого оригинала?', en: '<b>Questions for the debrief:</b> what kept subscribers — the catalogue or the habit? At what point did rising hours stop producing profit? What would the same base be worth without a single original?' },
  gameOverPlayAgain: { ru: 'Сыграть ещё раз', en: 'Play again' },
  gameOverCharts: { ru: 'Посмотреть графики', en: 'Look at the charts' },
  helpModalTitle: { ru: 'Как играть', en: 'How to play' },
  helpModalOk: { ru: 'Понятно', en: 'Got it' },
  restartTitle: { ru: 'Начать заново?', en: 'Start over?' },
  restartText: { ru: 'Текущая партия будет потеряна, рынок сгенерируется заново.', en: 'The current game will be lost and the market will be regenerated.' },
  restartYes: { ru: 'Да, заново', en: 'Yes, restart' },
  restartNo: { ru: 'Отмена', en: 'Cancel' },
};
